import { Effect } from "effect"
import { TimescaleClient } from "../Client.js"
import { QueueError } from "../Error.js"
import { quoteIdentifier, toSqlValue } from "../internal/sql.js"
import type { TableDefinition, ColumnDef, ConstraintDef, IndexDef, TriggerDef, IndexColumn } from "../schema/types.js"
import type { TriggerFunctionDefinition } from "../functions/types.js"
import type { SchemaDefinition } from "../migration/Generator.js"
import { jobNotifyFunction, jobQueue, jobWorkflows, jobSchedules, jobWorkers } from "./schema.js"

// ---------------------------------------------------------------------------
// DDL generators (mirrors migration/Generator.ts helpers for idempotent DDL)
// ---------------------------------------------------------------------------

const formatIndexColumn = (col: IndexColumn): string => {
  if (typeof col === "string") return quoteIdentifier(col)
  const isSimpleColumn = /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(col.expression)
  let s = isSimpleColumn ? quoteIdentifier(col.expression) : `(${col.expression})`
  if (col.opclass) s += ` ${col.opclass}`
  if (col.order) s += ` ${col.order}`
  if (col.nulls) s += ` NULLS ${col.nulls}`
  return s
}

const generateColumnSql = (c: ColumnDef): string => {
  let s = `${quoteIdentifier(c.name)} ${c.sqlType}`

  if (c.generated) {
    if (c.generated.type === "stored") {
      s += ` GENERATED ALWAYS AS (${c.generated.expression}) STORED`
    } else if (c.generated.mode === "always") {
      s += ` GENERATED ALWAYS AS IDENTITY`
    } else {
      s += ` GENERATED BY DEFAULT AS IDENTITY`
    }
  }

  if (c.isPrimaryKey) s += " PRIMARY KEY"
  if (c.isNotNull && !c.isPrimaryKey) s += " NOT NULL"
  if (c.isUnique) s += " UNIQUE"
  if (c.defaultValue !== undefined) s += ` DEFAULT ${toSqlValue(c.defaultValue)}`
  if (c.check) s += ` CHECK (${c.check})`
  if (c.references) {
    s += ` REFERENCES ${quoteIdentifier(c.references.table)}(${quoteIdentifier(c.references.column)})`
    if (c.onDelete) s += ` ON DELETE ${c.onDelete}`
    if (c.onUpdate) s += ` ON UPDATE ${c.onUpdate}`
  }

  return s
}

const generateConstraintSql = (constraint: ConstraintDef): string => {
  const quotedCols = constraint.columns.map(quoteIdentifier).join(", ")
  let sql = `CONSTRAINT ${quoteIdentifier(constraint.name)}`
  switch (constraint.type) {
    case "check":
      sql += ` CHECK (${constraint.expression})`
      break
    case "unique":
      sql += ` UNIQUE (${quotedCols})`
      break
    case "primaryKey":
      sql += ` PRIMARY KEY (${quotedCols})`
      break
    case "foreignKey": {
      const refCols = constraint.references!.columns.map(quoteIdentifier).join(", ")
      sql += ` FOREIGN KEY (${quotedCols}) REFERENCES ${quoteIdentifier(constraint.references!.table)}(${refCols})`
      if (constraint.onDelete) sql += ` ON DELETE ${constraint.onDelete}`
      if (constraint.onUpdate) sql += ` ON UPDATE ${constraint.onUpdate}`
      break
    }
  }
  return sql
}

const generateCreateTable = (def: TableDefinition): string => {
  const cols = Object.values(def.columns) as ColumnDef[]
  const colDefs = cols.map(generateColumnSql)
  const constraintDefs = def.constraints.map(generateConstraintSql)
  const allDefs = [...colDefs, ...constraintDefs]
  return `CREATE TABLE IF NOT EXISTS ${quoteIdentifier(def.name)} (\n  ${allDefs.join(",\n  ")}\n)`
}

const generateCreateIndex = (tableName: string, idx: IndexDef): string => {
  let sql = "CREATE"
  if (idx.unique) sql += " UNIQUE"
  sql += " INDEX IF NOT EXISTS"
  sql += ` ${quoteIdentifier(idx.name)} ON ${quoteIdentifier(tableName)}`
  sql += ` USING ${idx.type}`
  sql += ` (${idx.columns.map(formatIndexColumn).join(", ")})`
  if (idx.where) sql += ` WHERE (${idx.where})`
  return sql
}

const generateTriggerFunctionSql = (def: TriggerFunctionDefinition): string => {
  // Raw PL/pgSQL body — the transpiler cannot handle PERFORM pg_notify(...)
  return `CREATE OR REPLACE FUNCTION ${quoteIdentifier(def.name)}() RETURNS trigger AS $$
BEGIN
  PERFORM pg_notify('_tsdb_sdk_job_' || NEW.queue, json_build_object('id', NEW.id, 'status', NEW.status)::text);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql`
}

const generateDropTrigger = (tableName: string, triggerName: string): string =>
  `DROP TRIGGER IF EXISTS ${triggerName} ON ${quoteIdentifier(tableName)}`

const generateCreateTrigger = (tableName: string, trg: TriggerDef): string => {
  const eventParts = trg.events.map((e, i) => {
    if (e === "UPDATE" && trg.columns && trg.columns.length > 0 && i === trg.events.indexOf("UPDATE")) {
      return `UPDATE OF ${trg.columns.map(quoteIdentifier).join(", ")}`
    }
    return e
  })
  let sql = `CREATE TRIGGER ${trg.name} ${trg.timing} ${eventParts.join(" OR ")} ON ${quoteIdentifier(tableName)}`
  sql += ` FOR EACH ${trg.forEach}`
  if (trg.when) sql += ` WHEN (${trg.when})`
  sql += ` EXECUTE FUNCTION ${trg.functionName}()`
  return sql
}

// ---------------------------------------------------------------------------
// Convert all definitions into ordered DDL statements
// ---------------------------------------------------------------------------

const definitionsToSql = (): string[] => {
  const statements: string[] = []
  const defs: ReadonlyArray<SchemaDefinition> = [jobNotifyFunction, jobQueue, jobWorkflows, jobSchedules, jobWorkers]

  for (const def of defs) {
    if (def._tag === "TriggerFunction") {
      statements.push(generateTriggerFunctionSql(def as TriggerFunctionDefinition))
    } else if (def._tag === "Table") {
      const tableDef = def as TableDefinition
      statements.push(generateCreateTable(tableDef))

      for (const idx of tableDef.indexes) {
        statements.push(generateCreateIndex(tableDef.name, idx))
      }

      for (const trg of tableDef.triggers) {
        statements.push(generateDropTrigger(tableDef.name, trg.name))
        statements.push(generateCreateTrigger(tableDef.name, trg))
      }
    }
  }

  return statements
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

let initialized = false

export const ensureQueueTables: Effect.Effect<void, QueueError, TimescaleClient> =
  Effect.gen(function* () {
    if (initialized) return

    const client = yield* TimescaleClient

    for (const sql of definitionsToSql()) {
      yield* client.execute(sql)
    }

    initialized = true
  }).pipe(
    Effect.mapError((error) =>
      error instanceof QueueError
        ? error
        : new QueueError({ message: `Failed to create queue tables: ${String(error)}`, cause: error })
    )
  )

/** Reset the initialization flag (for testing) */
export const resetInitialized = () => { initialized = false }
