import type { MigrationFile, LoadMigrationOptions } from "./types.js"
import type { PersistedSnapshot } from "./DefinitionsSnapshot.js"

const INTEGRITY_SECRET = "tsdb-sdk:v1:do-not-manually-create-migrations:7f3a9c2e"

export const AI_WARNING_HEADER = `/**
 * ============================================================================
 * DO NOT EDIT THIS FILE MANUALLY
 * ============================================================================
 * This migration was auto-generated by timescaledb-sdk.
 * It contains an integrity hash verified at runtime.
 * Manual changes will cause the migration to be rejected.
 * @generated by timescaledb-sdk — DO NOT EDIT
 * ============================================================================
 */
`

export interface MigrationJournal {
  readonly version: 1
  readonly entries: ReadonlyArray<JournalEntry>
}

export interface JournalEntry {
  readonly index: number
  readonly name: string
  readonly timestamp: number
  readonly checksum: string
  readonly description?: string
}

const JOURNAL_FILE = "_journal.json"
const SNAPSHOT_FILE = "_snapshot.json"

export const readJournal = async (dir: string): Promise<MigrationJournal> => {
  const path = `${dir}/${JOURNAL_FILE}`
  const file = Bun.file(path)
  if (!(await file.exists())) {
    return { version: 1, entries: [] }
  }
  return file.json()
}

export const readSnapshot = async (dir: string): Promise<PersistedSnapshot | null> => {
  const path = `${dir}/${SNAPSHOT_FILE}`
  const file = Bun.file(path)
  if (!(await file.exists())) {
    return null
  }
  return file.json()
}

export const writeJournal = async (dir: string, journal: MigrationJournal): Promise<void> => {
  const path = `${dir}/${JOURNAL_FILE}`
  await Bun.write(path, JSON.stringify(journal, null, 2))
}

export const writeSnapshot = async (dir: string, snapshot: PersistedSnapshot): Promise<void> => {
  const path = `${dir}/${SNAPSHOT_FILE}`
  await Bun.write(path, JSON.stringify(snapshot, null, 2))
}

export const generateMigrationName = (idx: number, description?: string): string => {
  const padded = String(idx).padStart(4, "0")
  if (!description) return padded
  const slug = description
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_|_$/g, "")
    .slice(0, 60)
  return `${padded}_${slug}`
}

export const computeMigrationChecksum = (file: MigrationFile): string => {
  const hasher = new Bun.CryptoHasher("sha256")
  hasher.update(file.name)
  for (const sql of file.up) hasher.update(sql)
  for (const sql of file.down) hasher.update(sql)
  return hasher.digest("hex")
}

export const computeIntegrityHash = (file: MigrationFile): string => {
  const hasher = new Bun.CryptoHasher("sha256", INTEGRITY_SECRET)
  hasher.update(file.name)
  hasher.update(String(file.timestamp))
  for (const sql of file.up) hasher.update(sql)
  for (const sql of file.down) hasher.update(sql)
  if (file.description) hasher.update(file.description)
  return hasher.digest("hex")
}

export const verifyIntegrity = (file: MigrationFile, path: string): void => {
  const expected = computeIntegrityHash(file)
  if (file.integrity !== expected) {
    throw new Error(
      `Integrity verification failed for migration at ${path}. ` +
      `This file may have been manually created or tampered with. ` +
      `Use sealMigration() to authorize hand-written migration files.`
    )
  }
}

export const writeMigrationFile = async (dir: string, migration: MigrationFile): Promise<string> => {
  const fileName = `${migration.name}.ts`
  const filePath = `${dir}/${fileName}`

  const integrity = computeIntegrityHash(migration)

  const upArray = migration.up.map((sql) => `    ${JSON.stringify(sql)},`).join("\n")
  const downArray = migration.down.map((sql) => `    ${JSON.stringify(sql)},`).join("\n")

  let content = AI_WARNING_HEADER
  content += `import type { MigrationFile } from "timescaledb-sdk/migration"\n\n`
  content += `export default {\n`
  content += `  name: ${JSON.stringify(migration.name)},\n`
  content += `  timestamp: ${migration.timestamp},\n`
  content += `  up: [\n${upArray}\n  ],\n`
  content += `  down: [\n${downArray}\n  ],\n`
  if (migration.description) {
    content += `  description: ${JSON.stringify(migration.description)},\n`
  }
  content += `  integrity: ${JSON.stringify(integrity)},\n`
  content += `} satisfies MigrationFile\n`

  await Bun.write(filePath, content)
  return filePath
}

let _importCounter = 0

export const loadMigrationFile = async (path: string, options?: LoadMigrationOptions): Promise<MigrationFile> => {
  const mod = await import(`${path}?t=${Date.now()}-${++_importCounter}`)
  const file = mod.default as MigrationFile
  if (!file || !file.name || !Array.isArray(file.up) || !Array.isArray(file.down)) {
    throw new Error(`Invalid migration file: ${path}`)
  }

  if (!options?.trustOverride) {
    if (!file.integrity) {
      console.warn(`Migration ${path} has no integrity hash — it may predate integrity checking or was manually created.`)
    } else {
      verifyIntegrity(file, path)
    }
  }

  return file
}

export const loadAllMigrations = async (dir: string, options?: LoadMigrationOptions): Promise<ReadonlyArray<MigrationFile>> => {
  const journal = await readJournal(dir)
  const migrations: MigrationFile[] = []

  for (const entry of journal.entries) {
    const filePath = `${dir}/${entry.name}.ts`
    const file = await loadMigrationFile(filePath, options)
    const checksum = computeMigrationChecksum(file)
    if (checksum !== entry.checksum) {
      throw new Error(`Checksum mismatch for migration ${entry.name}: expected ${entry.checksum}, got ${checksum}`)
    }
    migrations.push(file)
  }

  return migrations
}

export const sealMigration = async (filePath: string): Promise<string> => {
  const file = await loadMigrationFile(filePath, { trustOverride: true })
  const dir = filePath.substring(0, filePath.lastIndexOf("/"))
  return writeMigrationFile(dir, file)
}
