import type { TableDefinition, HypertableDefinition, ColumnDef, ConstraintDef, IndexDef } from "../schema/types.js"
import type { SchemaSnapshot } from "./types.js"
import { toSqlValue, quoteIdentifier } from "../internal/sql.js"

export interface SchemaDiff {
  readonly tablesToCreate: ReadonlyArray<string>
  readonly tablesToDrop: ReadonlyArray<string>
  readonly columnsToAdd: ReadonlyArray<{ table: string; column: string; dataType: string; isNotNull: boolean; defaultValue: unknown }>
  readonly columnsToRemove: ReadonlyArray<{ table: string; column: string }>
  readonly columnsToAlter: ReadonlyArray<{ table: string; column: string; oldType: string; newType: string }>
  readonly hypertablesToCreate: ReadonlyArray<string>
}

export const diffSchema = (
  definitions: ReadonlyArray<TableDefinition | HypertableDefinition>,
  snapshot: SchemaSnapshot
): SchemaDiff => {
  const definedTables = new Set(definitions.map((d) => d.name))
  const snapshotTables = new Set(snapshot.tables.map((t) => t.name))
  const snapshotHypertables = new Set(snapshot.hypertables.map((h) => h.name))

  const tablesToCreate = definitions
    .filter((d) => !snapshotTables.has(d.name))
    .map((d) => d.name)

  const tablesToDrop = snapshot.tables
    .filter((t) => !definedTables.has(t.name) && !t.name.startsWith("_"))
    .map((t) => t.name)

  const columnsToAdd: Array<{ table: string; column: string; dataType: string; isNotNull: boolean; defaultValue: unknown }> = []
  const columnsToRemove: Array<{ table: string; column: string }> = []
  const columnsToAlter: Array<{ table: string; column: string; oldType: string; newType: string }> = []

  for (const def of definitions) {
    const existing = snapshot.tables.find((t) => t.name === def.name)
    if (!existing) continue

    const existingCols = new Map(existing.columns.map((c) => [c.name, c]))
    const definedCols = Object.values(def.columns) as ColumnDef[]

    for (const col of definedCols) {
      const existingCol = existingCols.get(col.name)
      if (!existingCol) {
        columnsToAdd.push({
          table: def.name,
          column: col.name,
          dataType: col.sqlType,
          isNotNull: col.isNotNull,
          defaultValue: col.defaultValue,
        })
      } else if (existingCol.dataType !== col.sqlType) {
        columnsToAlter.push({
          table: def.name,
          column: col.name,
          oldType: existingCol.dataType,
          newType: col.sqlType,
        })
      }
    }

    for (const [colName] of existingCols) {
      if (!definedCols.find((c) => c.name === colName)) {
        columnsToRemove.push({ table: def.name, column: colName })
      }
    }
  }

  const hypertablesToCreate = definitions
    .filter((d): d is HypertableDefinition => d._tag === "Hypertable" && !snapshotHypertables.has(d.name))
    .map((d) => d.name)

  return { tablesToCreate, tablesToDrop, columnsToAdd, columnsToRemove, columnsToAlter, hypertablesToCreate }
}

const generateColumnSql = (c: ColumnDef): string => {
  let s = `${quoteIdentifier(c.name)} ${c.sqlType}`

  if (c.generated) {
    if (c.generated.type === "stored") {
      s += ` GENERATED ALWAYS AS (${c.generated.expression}) STORED`
    } else if (c.generated.mode === "always") {
      s += ` GENERATED ALWAYS AS IDENTITY`
    } else {
      s += ` GENERATED BY DEFAULT AS IDENTITY`
    }
  }

  if (c.collation) {
    s += ` COLLATE ${quoteIdentifier(c.collation)}`
  }

  if (c.isPrimaryKey) s += " PRIMARY KEY"
  if (c.isNotNull && !c.isPrimaryKey) s += " NOT NULL"
  if (c.isUnique) s += " UNIQUE"
  if (c.defaultValue !== undefined) s += ` DEFAULT ${toSqlValue(c.defaultValue)}`

  if (c.check) {
    s += ` CHECK (${c.check})`
  }

  if (c.references) {
    s += ` REFERENCES ${quoteIdentifier(c.references.table)}(${quoteIdentifier(c.references.column)})`
    if (c.onDelete) s += ` ON DELETE ${c.onDelete}`
    if (c.onUpdate) s += ` ON UPDATE ${c.onUpdate}`
  }

  return s
}

const generateConstraintSql = (constraint: ConstraintDef): string => {
  const quotedCols = constraint.columns.map(quoteIdentifier).join(", ")

  let sql = `CONSTRAINT ${quoteIdentifier(constraint.name)}`

  switch (constraint.type) {
    case "check":
      sql += ` CHECK (${constraint.expression})`
      break
    case "unique":
      sql += ` UNIQUE (${quotedCols})`
      break
    case "primaryKey":
      sql += ` PRIMARY KEY (${quotedCols})`
      break
    case "foreignKey": {
      const refCols = constraint.references!.columns.map(quoteIdentifier).join(", ")
      sql += ` FOREIGN KEY (${quotedCols}) REFERENCES ${quoteIdentifier(constraint.references!.table)}(${refCols})`
      if (constraint.onDelete) sql += ` ON DELETE ${constraint.onDelete}`
      if (constraint.onUpdate) sql += ` ON UPDATE ${constraint.onUpdate}`
      break
    }
    case "exclude": {
      const elements = constraint.excludeElements!
        .map((e) => `${quoteIdentifier(e.column)} WITH ${e.operator}`)
        .join(", ")
      sql += ` EXCLUDE USING ${constraint.using} (${elements})`
      if (constraint.excludeWhere) sql += ` WHERE (${constraint.excludeWhere})`
      break
    }
  }

  if (constraint.deferrable) {
    sql += " DEFERRABLE"
    if (constraint.initiallyDeferred) sql += " INITIALLY DEFERRED"
    else sql += " INITIALLY IMMEDIATE"
  }

  return sql
}

const generateIndexSql = (tableName: string, idx: IndexDef): string => {
  let sql = "CREATE"
  if (idx.unique) sql += " UNIQUE"
  sql += " INDEX"
  if (idx.concurrently) sql += " CONCURRENTLY"
  sql += ` ${quoteIdentifier(idx.name)} ON ${quoteIdentifier(tableName)}`
  sql += ` USING ${idx.type}`
  sql += ` (${idx.columns.map(quoteIdentifier).join(", ")})`

  if (idx.include && idx.include.length > 0) {
    sql += ` INCLUDE (${idx.include.map(quoteIdentifier).join(", ")})`
  }

  if (idx.nullsNotDistinct) {
    sql += ` NULLS NOT DISTINCT`
  }

  if (idx.fillfactor) {
    sql += ` WITH (fillfactor = ${idx.fillfactor})`
  }

  if (idx.where) {
    sql += ` WHERE (${idx.where})`
  }

  return sql + ";"
}

export const generateMigrationSql = (diff: SchemaDiff, definitions: ReadonlyArray<TableDefinition | HypertableDefinition>): { up: string[]; down: string[] } => {
  const up: string[] = []
  const down: string[] = []

  for (const tableName of diff.tablesToCreate) {
    const def = definitions.find((d) => d.name === tableName)
    if (!def) continue

    const cols = Object.values(def.columns) as ColumnDef[]
    const colDefs = cols.map(generateColumnSql)

    // Add table-level constraints
    const constraintDefs = def.constraints.map(generateConstraintSql)

    const allDefs = [...colDefs, ...constraintDefs]

    let createSql = "CREATE"
    if (def.unlogged) createSql += " UNLOGGED"
    createSql += " TABLE"
    if (def.ifNotExists) createSql += " IF NOT EXISTS"
    createSql += ` ${quoteIdentifier(tableName)} (\n  ${allDefs.join(",\n  ")}\n);`

    up.push(createSql)
    down.push(`DROP TABLE IF EXISTS ${quoteIdentifier(tableName)};`)

    // Generate index creation statements
    for (const idx of def.indexes) {
      up.push(generateIndexSql(tableName, idx))
    }
  }

  for (const tableName of diff.hypertablesToCreate) {
    const def = definitions.find((d) => d.name === tableName) as HypertableDefinition | undefined
    if (!def) continue

    const config = def.hypertableConfig
    const args = [`'${tableName}'`, `'${config.timeColumn}'`]
    if (config.chunkInterval) {
      args.push(`chunk_time_interval => INTERVAL '${config.chunkInterval}'`)
    }
    if (config.createDefaultIndexes === false) {
      args.push(`create_default_indexes => FALSE`)
    }
    up.push(`SELECT create_hypertable(${args.join(", ")});`)

    // Space partitioning dimensions
    if (config.partitioning) {
      for (const part of config.partitioning) {
        const dimArgs = [`'${tableName}'`, `'${part.column}'`]
        if (part.numberOfPartitions) {
          dimArgs.push(String(part.numberOfPartitions))
        }
        up.push(`SELECT add_dimension(${dimArgs.join(", ")});`)
      }
    }

    // Compression policy
    if (config.compression) {
      const compParts: string[] = [`timescaledb.compress`]
      if (config.compression.segmentby && config.compression.segmentby.length > 0) {
        compParts.push(`timescaledb.compress_segmentby = '${config.compression.segmentby.join(", ")}'`)
      }
      if (config.compression.orderby && config.compression.orderby.length > 0) {
        const orderParts = config.compression.orderby.map((o) => {
          let s = o.column
          if (o.order) s += ` ${o.order}`
          if (o.nullsFirst !== undefined) s += o.nullsFirst ? " NULLS FIRST" : " NULLS LAST"
          return s
        })
        compParts.push(`timescaledb.compress_orderby = '${orderParts.join(", ")}'`)
      }
      up.push(`ALTER TABLE ${quoteIdentifier(tableName)} SET (${compParts.join(", ")});`)

      if (config.compression.after) {
        up.push(`SELECT add_compression_policy('${tableName}', INTERVAL '${config.compression.after}');`)
      }
    }

    // Retention policy
    if (config.retention) {
      up.push(`SELECT add_retention_policy('${tableName}', INTERVAL '${config.retention.dropAfter}');`)
    }
  }

  for (const tableName of diff.tablesToDrop) {
    up.push(`DROP TABLE IF EXISTS ${quoteIdentifier(tableName)};`)
    down.push(`-- Cannot auto-generate recreation of dropped table ${quoteIdentifier(tableName)}`)
  }

  for (const col of diff.columnsToAdd) {
    let sql = `ALTER TABLE ${quoteIdentifier(col.table)} ADD COLUMN ${quoteIdentifier(col.column)} ${col.dataType}`
    if (col.isNotNull && col.defaultValue !== undefined) sql += ` NOT NULL DEFAULT ${toSqlValue(col.defaultValue)}`
    else if (col.isNotNull) sql += ` NOT NULL`
    up.push(`${sql};`)
    down.push(`ALTER TABLE ${quoteIdentifier(col.table)} DROP COLUMN ${quoteIdentifier(col.column)};`)
  }

  for (const col of diff.columnsToRemove) {
    up.push(`ALTER TABLE ${quoteIdentifier(col.table)} DROP COLUMN ${quoteIdentifier(col.column)};`)
    down.push(`-- Cannot auto-generate re-addition of column ${quoteIdentifier(col.column)} on ${quoteIdentifier(col.table)}`)
  }

  for (const col of diff.columnsToAlter) {
    up.push(`ALTER TABLE ${quoteIdentifier(col.table)} ALTER COLUMN ${quoteIdentifier(col.column)} TYPE ${col.newType};`)
    down.push(`ALTER TABLE ${quoteIdentifier(col.table)} ALTER COLUMN ${quoteIdentifier(col.column)} TYPE ${col.oldType};`)
  }

  return { up, down }
}
