/**
 * ============================================================================
 * DO NOT EDIT THIS FILE MANUALLY
 * ============================================================================
 * This migration was auto-generated by timescaledb-sdk.
 * It contains an integrity hash verified at runtime.
 * Manual changes will cause the migration to be rejected.
 * @generated by timescaledb-sdk — DO NOT EDIT
 * ============================================================================
 */
import type { MigrationFile } from "timescaledb-sdk/migration"

export default {
  name: "0001_iot_analytics_schema",
  timestamp: 1772201612770,
  up: [
    "CREATE TYPE \"device_status\" AS ENUM ('online', 'offline', 'maintenance');",
    "CREATE TABLE \"devices\" (\n  \"id\" serial NOT NULL,\n  \"device_id\" varchar(128) NOT NULL,\n  \"name\" text NOT NULL,\n  \"location\" text,\n  \"status\" device_status,\n  \"metadata\" jsonb,\n  \"created_at\" timestamptz NOT NULL DEFAULT 'now()'\n);",
    "CREATE UNIQUE INDEX \"uq_devices_device_id\" ON \"devices\" USING btree (\"device_id\");",
    "CREATE TABLE \"sensor_readings\" (\n  \"time\" timestamptz NOT NULL,\n  \"device_id\" varchar(128) NOT NULL,\n  \"temperature\" double precision,\n  \"humidity\" double precision,\n  \"battery_level\" double precision,\n  CONSTRAINT \"chk_battery_range\" CHECK (\"battery_level\" IS NULL OR (\"battery_level\" >= 0 AND \"battery_level\" <= 100))\n);",
    "CREATE INDEX \"idx_readings_device_time\" ON \"sensor_readings\" USING btree (\"device_id\", \"time\");",
    "CREATE TABLE \"alerts\" (\n  \"id\" serial NOT NULL,\n  \"device_id\" varchar(128) NOT NULL,\n  \"severity\" text NOT NULL,\n  \"message\" text,\n  \"acknowledged\" boolean NOT NULL DEFAULT 'false',\n  \"created_at\" timestamptz NOT NULL DEFAULT 'now()'\n);",
    "CREATE INDEX \"idx_alerts_device_created\" ON \"alerts\" USING btree (\"device_id\", \"created_at\");",
    "SELECT create_hypertable('sensor_readings', 'time', chunk_time_interval => INTERVAL '7 days');",
    "ALTER TABLE \"sensor_readings\" SET (timescaledb.compress, timescaledb.compress_segmentby = 'device_id', timescaledb.compress_orderby = 'time DESC');",
    "SELECT add_compression_policy('sensor_readings', INTERVAL '30 days');",
    "CREATE MATERIALIZED VIEW \"hourly_readings\" WITH (timescaledb.continuous) AS\nSELECT time_bucket('1 hour', \"time\") AS \"bucket\",\n  \"device_id\",\n  AVG(temperature) AS \"avg_temp\",\n  AVG(humidity) AS \"avg_humidity\",\n  MIN(battery_level) AS \"min_battery\",\n  COUNT(*) AS \"reading_count\"\nFROM \"sensor_readings\"\nGROUP BY \"bucket\", \"device_id\";",
  ],
  down: [
    "DROP TYPE IF EXISTS \"device_status\";",
    "DROP TABLE IF EXISTS \"devices\";",
    "DROP TABLE IF EXISTS \"sensor_readings\";",
    "DROP TABLE IF EXISTS \"alerts\";",
    "DROP MATERIALIZED VIEW IF EXISTS \"hourly_readings\";",
  ],
  transactional: false,
  description: "IoT analytics schema",
  integrity: "66571a49667368db42c1ee8cdfb4bd41db82f9ed4135aaf0f3151be9f5838f7c",
} satisfies MigrationFile
