import { test, expect, describe, beforeEach, afterEach, jest } from "bun:test"
import { Effect } from "effect"
import { mkdtemp, rm } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { generate, rebuildSnapshot, migrationFileToEffect, loadAndRun } from "../../src/migration/Orchestrator.js"
import { SnapshotWarning, drainWarnings } from "../../src/migration/Snapshot.js"
import { migrate } from "../../src/migration/Runner.js"
import { readJournal, readSnapshot, writeSnapshot, writeJournal, writeMigrationFile, computeMigrationChecksum, computeIntegrityHash } from "../../src/migration/FileSystem.js"
import { definitionsToPersistedSnapshot } from "../../src/migration/DefinitionsSnapshot.js"
import { timestamptz, integer, doublePrecision, text, serial, boolean } from "../../src/schema/Column.js"
import { pgTable } from "../../src/schema/Table.js"
import { hypertable } from "../../src/schema/Hypertable.js"
import { pgEnum, enumColumn } from "../../src/schema/Enum.js"
import type { MigrationFile, Migration } from "../../src/migration/types.js"
import { MigrationError } from "../../src/Error.js"
import { mockClient } from "../setup/test-layers.js"
import { runTestWith } from "../helpers/effect-runner.js"

let dir: string

beforeEach(async () => {
  dir = await mkdtemp(join(tmpdir(), "tsdb-orch-"))
})

afterEach(async () => {
  await rm(dir, { recursive: true, force: true })
})

describe("generate()", () => {
  test("fresh directory creates first migration + journal + snapshot", async () => {
    const users = pgTable("users", {
      id: serial("id"),
      name: text("name").notNull(),
    })

    const result = await generate({
      definitions: [users],
      migrationsDir: dir,
      description: "create users table",
    })

    expect(result).not.toBeNull()
    expect(result!.migrationName).toBe("0001_create_users_table")
    expect(result!.up.length).toBeGreaterThan(0)
    expect(result!.up[0]).toContain('CREATE TABLE "users"')
    expect(result!.filePath).toContain("0001_create_users_table.ts")

    // Verify journal was written
    const journal = await readJournal(dir)
    expect(journal.entries.length).toBe(1)
    expect(journal.entries[0]!.name).toBe("0001_create_users_table")

    // Verify snapshot was written
    const snapshot = await readSnapshot(dir)
    expect(snapshot).not.toBeNull()
    expect(snapshot!.definitions.tables.length).toBe(1)

    // Verify migration file exists with integrity and warning header
    const fileContent = await Bun.file(result!.filePath).text()
    expect(fileContent).toContain("0001_create_users_table")
    expect(fileContent).toContain("satisfies MigrationFile")
    expect(fileContent).toContain("DO NOT EDIT THIS FILE MANUALLY")
    expect(fileContent).toContain("integrity:")
  })

  test("incremental migration from existing state", async () => {
    const users = pgTable("users", {
      id: serial("id"),
      name: text("name").notNull(),
    })

    // First generation
    await generate({
      definitions: [users],
      migrationsDir: dir,
      description: "create users",
    })

    // Add a column
    const usersV2 = pgTable("users", {
      id: serial("id"),
      name: text("name").notNull(),
      email: text("email").notNull(),
    })

    const result = await generate({
      definitions: [usersV2],
      migrationsDir: dir,
      description: "add email column",
    })

    expect(result).not.toBeNull()
    expect(result!.migrationName).toBe("0002_add_email_column")
    expect(result!.up.some((s) => s.includes("ADD COLUMN"))).toBe(true)
    expect(result!.up.some((s) => s.includes('"email"'))).toBe(true)

    const journal = await readJournal(dir)
    expect(journal.entries.length).toBe(2)
  })

  test("no changes returns null", async () => {
    const users = pgTable("users", {
      id: serial("id"),
      name: text("name").notNull(),
    })

    await generate({
      definitions: [users],
      migrationsDir: dir,
      description: "create users",
    })

    // Same definitions again
    const result = await generate({
      definitions: [users],
      migrationsDir: dir,
      description: "no changes",
    })

    expect(result).toBeNull()

    // Journal should still have 1 entry
    const journal = await readJournal(dir)
    expect(journal.entries.length).toBe(1)
  })

  test("rename hints produce RENAME SQL", async () => {
    const users = pgTable("users", {
      id: serial("id"),
      name: text("name").notNull(),
    })

    await generate({
      definitions: [users],
      migrationsDir: dir,
      description: "create users",
    })

    // Rename column
    const usersV2 = pgTable("users", {
      id: serial("id"),
      fullName: text("full_name").notNull().renamedFrom("name"),
    })

    const result = await generate({
      definitions: [usersV2],
      migrationsDir: dir,
      description: "rename name to full_name",
    })

    expect(result).not.toBeNull()
    expect(result!.up.some((s) => s.includes("RENAME COLUMN"))).toBe(true)
    expect(result!.up.some((s) => s.includes('"name" TO "full_name"'))).toBe(true)
  })

  test("table rename + column add in single migration", async () => {
    const users = pgTable("users", {
      id: serial("id"),
      name: text("name").notNull(),
    })

    await generate({
      definitions: [users],
      migrationsDir: dir,
      description: "create users",
    })

    // Rename table and add column
    const accounts = pgTable("accounts", {
      id: serial("id"),
      name: text("name").notNull(),
      email: text("email").notNull(),
    }, undefined, { renamedFrom: "users" })

    const result = await generate({
      definitions: [accounts],
      migrationsDir: dir,
      description: "rename users to accounts and add email",
    })

    expect(result).not.toBeNull()
    expect(result!.up.some((s) => s.includes('RENAME TO "accounts"'))).toBe(true)
    expect(result!.up.some((s) => s.includes('ADD COLUMN'))).toBe(true)
  })

  test("with enum definitions", async () => {
    const statusEnum = pgEnum("status", ["active", "inactive"] as const)
    const users = pgTable("users", {
      id: serial("id"),
      status: enumColumn(statusEnum, "status").notNull(),
    })

    const result = await generate({
      definitions: [statusEnum, users],
      migrationsDir: dir,
      description: "create users with status enum",
    })

    expect(result).not.toBeNull()
    expect(result!.up.some((s) => s.includes("CREATE TYPE"))).toBe(true)
    expect(result!.up.some((s) => s.includes("CREATE TABLE"))).toBe(true)

    // Enum before table
    const enumIdx = result!.up.findIndex((s) => s.includes("CREATE TYPE"))
    const tableIdx = result!.up.findIndex((s) => s.includes("CREATE TABLE"))
    expect(enumIdx).toBeLessThan(tableIdx)
  })

  test("with hypertable", async () => {
    const metrics = hypertable("metrics", {
      time: timestamptz("time").notNull(),
      value: doublePrecision("value"),
    }, {
      timeColumn: "time",
      chunkInterval: "1 day",
    })

    const result = await generate({
      definitions: [metrics],
      migrationsDir: dir,
      description: "create metrics hypertable",
    })

    expect(result).not.toBeNull()
    expect(result!.up.some((s) => s.includes("CREATE TABLE"))).toBe(true)
    expect(result!.up.some((s) => s.includes("create_hypertable"))).toBe(true)
  })

  test("no description produces index-only name", async () => {
    const users = pgTable("users", { id: serial("id") })

    const result = await generate({
      definitions: [users],
      migrationsDir: dir,
    })

    expect(result).not.toBeNull()
    expect(result!.migrationName).toBe("0001")
  })
})

describe("migrationFileToEffect()", () => {
  test("produces valid Migration object", () => {
    const file: MigrationFile = {
      name: "0001_test",
      timestamp: 0,
      up: ["SELECT 1;"],
      down: ["SELECT 2;"],
    }

    const migration = migrationFileToEffect(file)
    expect(migration.name).toBe("0001_test")
    expect(migration.up).toBeDefined()
    expect(migration.down).toBeDefined()
  })
})

describe("LoadMigrationOptions flow", () => {
  test("loadAndRun rejects tampered migration file", async () => {
    const migration: MigrationFile = {
      name: "0001_create_items",
      timestamp: 1700000000000,
      up: ['CREATE TABLE "items" ("id" serial NOT NULL);'],
      down: ['DROP TABLE IF EXISTS "items";'],
    }

    // Write valid migration and get its checksum
    await writeMigrationFile(dir, migration)
    const checksum = computeMigrationChecksum(migration)
    const originalIntegrity = computeIntegrityHash(migration)

    // Now overwrite with tampered SQL but original integrity hash
    const filePath = `${dir}/${migration.name}.ts`
    let content = `import type { MigrationFile } from "timescaledb-sdk/migration"\n\n`
    content += `export default {\n`
    content += `  name: ${JSON.stringify(migration.name)},\n`
    content += `  timestamp: ${migration.timestamp},\n`
    content += `  up: ["DROP TABLE items;"],\n`
    content += `  down: [],\n`
    content += `  integrity: ${JSON.stringify(originalIntegrity)},\n`
    content += `} satisfies MigrationFile\n`
    await Bun.write(filePath, content)

    // Journal still has the original checksum — integrity check should fail first
    await writeJournal(dir, {
      version: 1,
      entries: [{ index: 1, name: migration.name, timestamp: migration.timestamp, checksum }],
    })

    const layer = mockClient()
    const result = Effect.runPromise(
      Effect.provide(loadAndRun(dir), layer)
    )
    expect(result).rejects.toThrow("Integrity verification failed")
  })

  test("loadAndRun with trustOverride skips integrity check", async () => {
    const migration: MigrationFile = {
      name: "0001_create_stuff",
      timestamp: 1700000000000,
      up: ["SELECT 1;"],
      down: [],
    }

    // Write a hand-written file with no integrity
    const filePath = `${dir}/${migration.name}.ts`
    let content = `import type { MigrationFile } from "timescaledb-sdk/migration"\n\n`
    content += `export default {\n`
    content += `  name: ${JSON.stringify(migration.name)},\n`
    content += `  timestamp: ${migration.timestamp},\n`
    content += `  up: ["SELECT 1;"],\n`
    content += `  down: [],\n`
    content += `} satisfies MigrationFile\n`
    await Bun.write(filePath, content)

    // Load once to get the correct checksum for the journal
    const { loadMigrationFile } = await import("../../src/migration/FileSystem.js")
    const loaded = await loadMigrationFile(filePath, { trustOverride: true })
    const checksum = computeMigrationChecksum(loaded)

    await writeJournal(dir, {
      version: 1,
      entries: [{ index: 1, name: migration.name, timestamp: migration.timestamp, checksum }],
    })

    // Mock client that handles advisory lock + migration queries
    const layer = mockClient({
      execute: <A = unknown>(query: string, _params?: ReadonlyArray<unknown>) => {
        if (query.includes("pg_try_advisory_lock")) {
          return Effect.succeed([{ pg_try_advisory_lock: true }] as ReadonlyArray<A>)
        }
        if (query.includes("pg_advisory_unlock")) {
          return Effect.succeed([{ pg_advisory_unlock: true }] as ReadonlyArray<A>)
        }
        // getAppliedMigrations — return empty (no migrations applied yet)
        if (query.includes("SELECT * FROM") && query.includes("_timescaledb_sdk_migrations")) {
          return Effect.succeed([] as ReadonlyArray<A>)
        }
        // All other queries (CREATE TABLE, INSERT, SELECT 1) — return empty
        return Effect.succeed([] as ReadonlyArray<A>)
      },
    })

    // With trustOverride, integrity check is skipped — should succeed with mock client
    const applied = await runTestWith(
      loadAndRun(dir, { trustOverride: true }),
      layer
    )
    expect(applied).toEqual(["0001_create_stuff"])
  })
})

// ============================================
// 5.5 — Lock Release and Transaction Wrapping
// ============================================
describe("migrate() — advisory lock release on failure", () => {
  test("migration failure → lock still released", async () => {
    const lockReleased = { value: false }

    const layer = mockClient({
      execute: <A = unknown>(query: string, _params?: ReadonlyArray<unknown>) => {
        if (query.includes("pg_try_advisory_lock")) {
          return Effect.succeed([{ pg_try_advisory_lock: true }] as ReadonlyArray<A>)
        }
        if (query.includes("pg_advisory_unlock")) {
          lockReleased.value = true
          return Effect.succeed([{ pg_advisory_unlock: true }] as ReadonlyArray<A>)
        }
        if (query.includes("CREATE TABLE IF NOT EXISTS")) {
          return Effect.succeed([] as ReadonlyArray<A>)
        }
        if (query.includes("SELECT * FROM") && query.includes("_timescaledb_sdk_migrations")) {
          return Effect.succeed([] as ReadonlyArray<A>)
        }
        if (query.includes("DELIBERATE_FAIL")) {
          return Effect.fail(new MigrationError({ message: "Deliberate failure" }))
        }
        return Effect.succeed([] as ReadonlyArray<A>)
      },
    })

    const { TimescaleClient } = await import("../../src/Client.js")

    const failingMigration: Migration = {
      name: "0001_fail",
      checksum: "abc123",
      up: Effect.gen(function* () {
        const client = yield* TimescaleClient
        yield* client.execute("DELIBERATE_FAIL")
      }),
      down: Effect.succeed(void 0),
    }

    const result = Effect.runPromise(
      Effect.provide(migrate([failingMigration]), layer)
    )

    await expect(result).rejects.toThrow()
    expect(lockReleased.value).toBe(true)
  })
})

describe("migrationFileToEffect() — transaction wrapping", () => {
  test("withTransaction is called when transactional is not false", async () => {
    let transactionUsed = false

    const layer = mockClient({
      execute: <A = unknown>(_query: string, _params?: ReadonlyArray<unknown>) =>
        Effect.succeed([] as ReadonlyArray<A>),
      withTransaction: <A, E, R>(effect: Effect.Effect<A, E, R>) => {
        transactionUsed = true
        return effect as any
      },
    })

    const file: MigrationFile = {
      name: "0001_test",
      timestamp: 0,
      up: ["SELECT 1;"],
      down: [],
    }

    const migration = migrationFileToEffect(file)
    await runTestWith(migration.up, layer)
    expect(transactionUsed).toBe(true)
  })

  test("withTransaction is NOT called when transactional is false", async () => {
    let transactionUsed = false

    const layer = mockClient({
      execute: <A = unknown>(_query: string, _params?: ReadonlyArray<unknown>) =>
        Effect.succeed([] as ReadonlyArray<A>),
      withTransaction: <A, E, R>(effect: Effect.Effect<A, E, R>) => {
        transactionUsed = true
        return effect as any
      },
    })

    const file: MigrationFile = {
      name: "0001_test",
      timestamp: 0,
      up: ["SELECT 1;"],
      down: [],
      transactional: false,
    }

    const migration = migrationFileToEffect(file)
    await runTestWith(migration.up, layer)
    expect(transactionUsed).toBe(false)
  })
})

// ============================================
// 5.6 — Dry-run Mode
// ============================================
describe("loadAndRun() — dry-run mode", () => {
  test("dryRun: true returns pending migration names without executing", async () => {
    const migration: MigrationFile = {
      name: "0001_create_stuff",
      timestamp: 1700000000000,
      up: ["CREATE TABLE stuff (id serial);"],
      down: ["DROP TABLE stuff;"],
    }

    await writeMigrationFile(dir, migration)
    const checksum = computeMigrationChecksum(migration)

    await writeJournal(dir, {
      version: 1,
      entries: [{ index: 1, name: migration.name, timestamp: migration.timestamp, checksum }],
    })

    let executeCount = 0

    const layer = mockClient({
      execute: <A = unknown>(query: string, _params?: ReadonlyArray<unknown>) => {
        if (query.includes("pg_try_advisory_lock")) {
          return Effect.succeed([{ pg_try_advisory_lock: true }] as ReadonlyArray<A>)
        }
        if (query.includes("pg_advisory_unlock")) {
          return Effect.succeed([{ pg_advisory_unlock: true }] as ReadonlyArray<A>)
        }
        if (query.includes("CREATE TABLE IF NOT EXISTS")) {
          return Effect.succeed([] as ReadonlyArray<A>)
        }
        if (query.includes("SELECT * FROM") && query.includes("_timescaledb_sdk_migrations")) {
          return Effect.succeed([] as ReadonlyArray<A>)
        }
        if (query.includes("CREATE TABLE stuff")) {
          executeCount++
        }
        return Effect.succeed([] as ReadonlyArray<A>)
      },
    })

    const result = await runTestWith(
      loadAndRun(dir, { trustOverride: true, dryRun: true }),
      layer
    )

    // Should return the pending migration name
    expect(result).toEqual(["0001_create_stuff"])
    // Should NOT have executed the actual migration SQL
    expect(executeCount).toBe(0)
  })
})

describe("end-to-end generate workflow", () => {
  test("three-step schema evolution", async () => {
    // Step 1: Create initial schema
    const usersV1 = pgTable("users", {
      id: serial("id"),
      name: text("name").notNull(),
    })

    const r1 = await generate({
      definitions: [usersV1],
      migrationsDir: dir,
      description: "initial schema",
    })
    expect(r1).not.toBeNull()
    expect(r1!.up.some((s) => s.includes("CREATE TABLE"))).toBe(true)

    // Step 2: Add column
    const usersV2 = pgTable("users", {
      id: serial("id"),
      name: text("name").notNull(),
      email: text("email"),
    })

    const r2 = await generate({
      definitions: [usersV2],
      migrationsDir: dir,
      description: "add email",
    })
    expect(r2).not.toBeNull()
    expect(r2!.up.some((s) => s.includes("ADD COLUMN"))).toBe(true)

    // Step 3: Rename column
    const usersV3 = pgTable("users", {
      id: serial("id"),
      fullName: text("full_name").notNull().renamedFrom("name"),
      email: text("email"),
    })

    const r3 = await generate({
      definitions: [usersV3],
      migrationsDir: dir,
      description: "rename name to full_name",
    })
    expect(r3).not.toBeNull()
    expect(r3!.up.some((s) => s.includes("RENAME COLUMN"))).toBe(true)

    // Verify final state
    const journal = await readJournal(dir)
    expect(journal.entries.length).toBe(3)
    expect(journal.entries[0]!.name).toBe("0001_initial_schema")
    expect(journal.entries[1]!.name).toBe("0002_add_email")
    expect(journal.entries[2]!.name).toBe("0003_rename_name_to_full_name")

    const snapshot = await readSnapshot(dir)
    expect(snapshot!.definitions.tables[0]!.columns.find((c) => c.name === "full_name")).toBeDefined()
    expect(snapshot!.definitions.tables[0]!.columns.find((c) => c.name === "name")).toBeUndefined()
  })
})

// =============================================================================
// C1: Snapshot warning infrastructure tests
// =============================================================================

describe("Snapshot warnings (C1)", () => {
  test("SnapshotWarning has correct structure", () => {
    const w = new SnapshotWarning("constraints", "Permission denied querying constraints")
    expect(w._tag).toBe("SnapshotWarning")
    expect(w.query).toBe("constraints")
    expect(w.message).toContain("Permission denied")
  })

  test("drainWarnings clears accumulated warnings", () => {
    // drain any leftover from other tests
    drainWarnings()
    const drained = drainWarnings()
    expect(drained.length).toBe(0)
  })
})

// =============================================================================
// C2: Atomic generate() tests
// =============================================================================

describe("Atomic generate() (C2)", () => {
  test("generate() writes all 3 files atomically", async () => {
    const users = pgTable("users", {
      id: serial("id"),
      name: text("name").notNull(),
    })

    const result = await generate({
      definitions: [users],
      migrationsDir: dir,
      description: "initial",
    })

    expect(result).not.toBeNull()

    // All 3 files should exist
    const migFile = Bun.file(result!.filePath)
    const journalFile = Bun.file(`${dir}/_journal.json`)
    const snapshotFile = Bun.file(`${dir}/_snapshot.json`)

    expect(await migFile.exists()).toBe(true)
    expect(await journalFile.exists()).toBe(true)
    expect(await snapshotFile.exists()).toBe(true)

    // No temp files should remain
    const tmpMig = Bun.file(`${result!.filePath}.tmp`)
    const tmpJournal = Bun.file(`${dir}/_journal.json.tmp`)
    const tmpSnapshot = Bun.file(`${dir}/_snapshot.json.tmp`)

    expect(await tmpMig.exists()).toBe(false)
    expect(await tmpJournal.exists()).toBe(false)
    expect(await tmpSnapshot.exists()).toBe(false)
  })

  test("journal and snapshot are consistent after atomic write", async () => {
    const users = pgTable("users", {
      id: serial("id"),
      name: text("name").notNull(),
    })

    await generate({
      definitions: [users],
      migrationsDir: dir,
      description: "initial",
    })

    const journal = await readJournal(dir)
    const snapshot = await readSnapshot(dir)

    expect(journal.entries.length).toBe(1)
    expect(journal.entries[0]!.name).toBe("0001_initial")
    expect(snapshot).not.toBeNull()
    expect(snapshot!.definitions.tables.length).toBe(1)
    expect(snapshot!.definitions.tables[0]!.name).toBe("users")
  })
})

// =============================================================================
// rebuildSnapshot() tests
// =============================================================================

describe("rebuildSnapshot()", () => {
  test("rebuilds snapshot from definitions (options form)", async () => {
    const users = pgTable("users", {
      id: serial("id"),
      name: text("name").notNull(),
    })

    const result = await rebuildSnapshot({
      definitions: [users],
      migrationsDir: dir,
    })

    expect(result.version).toBe(1)
    expect(result.definitions.tables.length).toBe(1)
    expect(result.definitions.tables[0]!.name).toBe("users")
    expect(result.generatedAt).toBeDefined()

    // Verify persisted to disk
    const persisted = await readSnapshot(dir)
    expect(persisted).not.toBeNull()
    expect(persisted!.definitions.tables.length).toBe(1)
    expect(persisted!.definitions.tables[0]!.name).toBe("users")
  })

  test("rebuilds snapshot from ResolvedConfig", async () => {
    const users = pgTable("users", {
      id: serial("id"),
      name: text("name").notNull(),
    })

    // Minimal ResolvedConfig-like object
    const config = {
      definitions: [users],
      migrations: { dir, advisoryLockId: 123456789, trackingTable: "_timescaledb_sdk_migrations", transactional: true },
      schema: [],
      features: {},
      connection: null,
      session: null,
      defaults: null,
      queue: { enabled: false, defaultMaxAttempts: 1, defaultPriority: 0 },
    } as any

    const result = await rebuildSnapshot(config)

    expect(result.version).toBe(1)
    expect(result.definitions.tables.length).toBe(1)
    expect(result.definitions.tables[0]!.name).toBe("users")
  })

  test("creates directory if it doesn't exist", async () => {
    const nestedDir = join(dir, "sub", "nested")
    const users = pgTable("users", {
      id: serial("id"),
    })

    const result = await rebuildSnapshot({
      definitions: [users],
      migrationsDir: nestedDir,
    })

    expect(result.version).toBe(1)
    const persisted = await readSnapshot(nestedDir)
    expect(persisted).not.toBeNull()
  })

  test("overwrites stale snapshot with updated definitions", async () => {
    const usersV1 = pgTable("users", {
      id: serial("id"),
      name: text("name").notNull(),
    })

    // Generate V1
    await generate({
      definitions: [usersV1],
      migrationsDir: dir,
      description: "v1",
    })

    const snapshotV1 = await readSnapshot(dir)
    expect(snapshotV1!.definitions.tables[0]!.columns.find((c) => c.name === "email")).toBeUndefined()

    // Rebuild with V2 definitions
    const usersV2 = pgTable("users", {
      id: serial("id"),
      name: text("name").notNull(),
      email: text("email").notNull(),
    })

    await rebuildSnapshot({
      definitions: [usersV2],
      migrationsDir: dir,
    })

    const snapshotV2 = await readSnapshot(dir)
    expect(snapshotV2!.definitions.tables[0]!.columns.find((c) => c.name === "email")).toBeDefined()
  })
})

// =============================================================================
// generate() consistency check tests
// =============================================================================

describe("generate() consistency check", () => {
  test("warns when snapshot is newer than latest journal entry", async () => {
    const warnSpy = jest.spyOn(console, "warn").mockImplementation(() => {})

    const users = pgTable("users", {
      id: serial("id"),
      name: text("name").notNull(),
    })

    // Generate initial migration normally
    await generate({
      definitions: [users],
      migrationsDir: dir,
    })

    warnSpy.mockClear()

    // Reset journal to empty but leave snapshot (simulating manual journal reset)
    await writeJournal(dir, {
      version: 1,
      entries: [{ index: 1, name: "0001", timestamp: Date.now() - 60000, checksum: "abc" }],
    })

    // Write a snapshot with a much newer generatedAt
    const futureSnapshot = definitionsToPersistedSnapshot([users])
    await writeSnapshot(dir, {
      ...futureSnapshot,
      generatedAt: new Date(Date.now() + 60000).toISOString(),
    })

    // Add a column so there's something to diff
    const usersV2 = pgTable("users", {
      id: serial("id"),
      name: text("name").notNull(),
      email: text("email"),
    })

    await generate({
      definitions: [usersV2],
      migrationsDir: dir,
      description: "add email",
    })

    expect(warnSpy).toHaveBeenCalledWith(
      expect.stringContaining("newer than the latest journal entry")
    )
    expect(warnSpy).toHaveBeenCalledWith(
      expect.stringContaining("rebuildSnapshot()")
    )

    warnSpy.mockRestore()
  })

  test("warns when journal has entries but snapshot is missing", async () => {
    const warnSpy = jest.spyOn(console, "warn").mockImplementation(() => {})

    const users = pgTable("users", {
      id: serial("id"),
      name: text("name").notNull(),
    })

    // Write journal with an entry but no snapshot file
    await writeJournal(dir, {
      version: 1,
      entries: [{ index: 1, name: "0001_initial", timestamp: Date.now(), checksum: "abc" }],
    })

    await generate({
      definitions: [users],
      migrationsDir: dir,
      description: "add users",
    })

    expect(warnSpy).toHaveBeenCalledWith(
      expect.stringContaining("_journal.json has 1 entries but _snapshot.json is missing")
    )
    expect(warnSpy).toHaveBeenCalledWith(
      expect.stringContaining("rebuildSnapshot()")
    )

    warnSpy.mockRestore()
  })

  test("no warning when journal and snapshot are in sync", async () => {
    const warnSpy = jest.spyOn(console, "warn").mockImplementation(() => {})

    const users = pgTable("users", {
      id: serial("id"),
      name: text("name").notNull(),
    })

    // Normal generate — should not warn
    await generate({
      definitions: [users],
      migrationsDir: dir,
      description: "initial",
    })

    // Second generate with changes — still should not warn
    const usersV2 = pgTable("users", {
      id: serial("id"),
      name: text("name").notNull(),
      email: text("email"),
    })

    await generate({
      definitions: [usersV2],
      migrationsDir: dir,
      description: "add email",
    })

    expect(warnSpy).not.toHaveBeenCalled()

    warnSpy.mockRestore()
  })

  test("no warning on first generation (empty directory)", async () => {
    const warnSpy = jest.spyOn(console, "warn").mockImplementation(() => {})

    const users = pgTable("users", {
      id: serial("id"),
      name: text("name").notNull(),
    })

    await generate({
      definitions: [users],
      migrationsDir: dir,
      description: "initial",
    })

    expect(warnSpy).not.toHaveBeenCalled()

    warnSpy.mockRestore()
  })
})
