import { test, expect, describe, beforeEach, afterEach } from "bun:test"
import { Effect } from "effect"
import { mkdtemp, rm } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { generate, migrationFileToEffect, loadAndRun } from "../../src/migration/Orchestrator.js"
import { readJournal, readSnapshot, writeJournal, writeMigrationFile, computeMigrationChecksum, computeIntegrityHash } from "../../src/migration/FileSystem.js"
import { timestamptz, integer, doublePrecision, text, serial, boolean } from "../../src/schema/Column.js"
import { pgTable } from "../../src/schema/Table.js"
import { hypertable } from "../../src/schema/Hypertable.js"
import { pgEnum, enumColumn } from "../../src/schema/Enum.js"
import type { MigrationFile } from "../../src/migration/types.js"
import { mockClient } from "../setup/test-layers.js"
import { runTestWith } from "../helpers/effect-runner.js"

let dir: string

beforeEach(async () => {
  dir = await mkdtemp(join(tmpdir(), "tsdb-orch-"))
})

afterEach(async () => {
  await rm(dir, { recursive: true, force: true })
})

describe("generate()", () => {
  test("fresh directory creates first migration + journal + snapshot", async () => {
    const users = pgTable("users", {
      id: serial("id"),
      name: text("name").notNull(),
    })

    const result = await generate({
      definitions: [users],
      migrationsDir: dir,
      description: "create users table",
    })

    expect(result).not.toBeNull()
    expect(result!.migrationName).toBe("0001_create_users_table")
    expect(result!.up.length).toBeGreaterThan(0)
    expect(result!.up[0]).toContain('CREATE TABLE "users"')
    expect(result!.filePath).toContain("0001_create_users_table.ts")

    // Verify journal was written
    const journal = await readJournal(dir)
    expect(journal.entries.length).toBe(1)
    expect(journal.entries[0]!.name).toBe("0001_create_users_table")

    // Verify snapshot was written
    const snapshot = await readSnapshot(dir)
    expect(snapshot).not.toBeNull()
    expect(snapshot!.definitions.tables.length).toBe(1)

    // Verify migration file exists with integrity and warning header
    const fileContent = await Bun.file(result!.filePath).text()
    expect(fileContent).toContain("0001_create_users_table")
    expect(fileContent).toContain("satisfies MigrationFile")
    expect(fileContent).toContain("DO NOT EDIT THIS FILE MANUALLY")
    expect(fileContent).toContain("integrity:")
  })

  test("incremental migration from existing state", async () => {
    const users = pgTable("users", {
      id: serial("id"),
      name: text("name").notNull(),
    })

    // First generation
    await generate({
      definitions: [users],
      migrationsDir: dir,
      description: "create users",
    })

    // Add a column
    const usersV2 = pgTable("users", {
      id: serial("id"),
      name: text("name").notNull(),
      email: text("email").notNull(),
    })

    const result = await generate({
      definitions: [usersV2],
      migrationsDir: dir,
      description: "add email column",
    })

    expect(result).not.toBeNull()
    expect(result!.migrationName).toBe("0002_add_email_column")
    expect(result!.up.some((s) => s.includes("ADD COLUMN"))).toBe(true)
    expect(result!.up.some((s) => s.includes('"email"'))).toBe(true)

    const journal = await readJournal(dir)
    expect(journal.entries.length).toBe(2)
  })

  test("no changes returns null", async () => {
    const users = pgTable("users", {
      id: serial("id"),
      name: text("name").notNull(),
    })

    await generate({
      definitions: [users],
      migrationsDir: dir,
      description: "create users",
    })

    // Same definitions again
    const result = await generate({
      definitions: [users],
      migrationsDir: dir,
      description: "no changes",
    })

    expect(result).toBeNull()

    // Journal should still have 1 entry
    const journal = await readJournal(dir)
    expect(journal.entries.length).toBe(1)
  })

  test("rename hints produce RENAME SQL", async () => {
    const users = pgTable("users", {
      id: serial("id"),
      name: text("name").notNull(),
    })

    await generate({
      definitions: [users],
      migrationsDir: dir,
      description: "create users",
    })

    // Rename column
    const usersV2 = pgTable("users", {
      id: serial("id"),
      fullName: text("full_name").notNull().renamedFrom("name"),
    })

    const result = await generate({
      definitions: [usersV2],
      migrationsDir: dir,
      description: "rename name to full_name",
    })

    expect(result).not.toBeNull()
    expect(result!.up.some((s) => s.includes("RENAME COLUMN"))).toBe(true)
    expect(result!.up.some((s) => s.includes('"name" TO "full_name"'))).toBe(true)
  })

  test("table rename + column add in single migration", async () => {
    const users = pgTable("users", {
      id: serial("id"),
      name: text("name").notNull(),
    })

    await generate({
      definitions: [users],
      migrationsDir: dir,
      description: "create users",
    })

    // Rename table and add column
    const accounts = pgTable("accounts", {
      id: serial("id"),
      name: text("name").notNull(),
      email: text("email").notNull(),
    }, undefined, { renamedFrom: "users" })

    const result = await generate({
      definitions: [accounts],
      migrationsDir: dir,
      description: "rename users to accounts and add email",
    })

    expect(result).not.toBeNull()
    expect(result!.up.some((s) => s.includes('RENAME TO "accounts"'))).toBe(true)
    expect(result!.up.some((s) => s.includes('ADD COLUMN'))).toBe(true)
  })

  test("with enum definitions", async () => {
    const statusEnum = pgEnum("status", ["active", "inactive"] as const)
    const users = pgTable("users", {
      id: serial("id"),
      status: enumColumn(statusEnum, "status").notNull(),
    })

    const result = await generate({
      definitions: [statusEnum, users],
      migrationsDir: dir,
      description: "create users with status enum",
    })

    expect(result).not.toBeNull()
    expect(result!.up.some((s) => s.includes("CREATE TYPE"))).toBe(true)
    expect(result!.up.some((s) => s.includes("CREATE TABLE"))).toBe(true)

    // Enum before table
    const enumIdx = result!.up.findIndex((s) => s.includes("CREATE TYPE"))
    const tableIdx = result!.up.findIndex((s) => s.includes("CREATE TABLE"))
    expect(enumIdx).toBeLessThan(tableIdx)
  })

  test("with hypertable", async () => {
    const metrics = hypertable("metrics", {
      time: timestamptz("time").notNull(),
      value: doublePrecision("value"),
    }, {
      timeColumn: "time",
      chunkInterval: "1 day",
    })

    const result = await generate({
      definitions: [metrics],
      migrationsDir: dir,
      description: "create metrics hypertable",
    })

    expect(result).not.toBeNull()
    expect(result!.up.some((s) => s.includes("CREATE TABLE"))).toBe(true)
    expect(result!.up.some((s) => s.includes("create_hypertable"))).toBe(true)
  })

  test("no description produces index-only name", async () => {
    const users = pgTable("users", { id: serial("id") })

    const result = await generate({
      definitions: [users],
      migrationsDir: dir,
    })

    expect(result).not.toBeNull()
    expect(result!.migrationName).toBe("0001")
  })
})

describe("migrationFileToEffect()", () => {
  test("produces valid Migration object", () => {
    const file: MigrationFile = {
      name: "0001_test",
      timestamp: 0,
      up: ["SELECT 1;"],
      down: ["SELECT 2;"],
    }

    const migration = migrationFileToEffect(file)
    expect(migration.name).toBe("0001_test")
    expect(migration.up).toBeDefined()
    expect(migration.down).toBeDefined()
  })
})

describe("LoadMigrationOptions flow", () => {
  test("loadAndRun rejects tampered migration file", async () => {
    const migration: MigrationFile = {
      name: "0001_create_items",
      timestamp: 1700000000000,
      up: ['CREATE TABLE "items" ("id" serial NOT NULL);'],
      down: ['DROP TABLE IF EXISTS "items";'],
    }

    // Write valid migration and get its checksum
    await writeMigrationFile(dir, migration)
    const checksum = computeMigrationChecksum(migration)
    const originalIntegrity = computeIntegrityHash(migration)

    // Now overwrite with tampered SQL but original integrity hash
    const filePath = `${dir}/${migration.name}.ts`
    let content = `import type { MigrationFile } from "timescaledb-sdk/migration"\n\n`
    content += `export default {\n`
    content += `  name: ${JSON.stringify(migration.name)},\n`
    content += `  timestamp: ${migration.timestamp},\n`
    content += `  up: ["DROP TABLE items;"],\n`
    content += `  down: [],\n`
    content += `  integrity: ${JSON.stringify(originalIntegrity)},\n`
    content += `} satisfies MigrationFile\n`
    await Bun.write(filePath, content)

    // Journal still has the original checksum — integrity check should fail first
    await writeJournal(dir, {
      version: 1,
      entries: [{ index: 1, name: migration.name, timestamp: migration.timestamp, checksum }],
    })

    const layer = mockClient()
    const result = Effect.runPromise(
      Effect.provide(loadAndRun(dir), layer)
    )
    expect(result).rejects.toThrow("Integrity verification failed")
  })

  test("loadAndRun with trustOverride skips integrity check", async () => {
    const migration: MigrationFile = {
      name: "0001_create_stuff",
      timestamp: 1700000000000,
      up: ["SELECT 1;"],
      down: [],
    }

    // Write a hand-written file with no integrity
    const filePath = `${dir}/${migration.name}.ts`
    let content = `import type { MigrationFile } from "timescaledb-sdk/migration"\n\n`
    content += `export default {\n`
    content += `  name: ${JSON.stringify(migration.name)},\n`
    content += `  timestamp: ${migration.timestamp},\n`
    content += `  up: ["SELECT 1;"],\n`
    content += `  down: [],\n`
    content += `} satisfies MigrationFile\n`
    await Bun.write(filePath, content)

    // Load once to get the correct checksum for the journal
    const { loadMigrationFile } = await import("../../src/migration/FileSystem.js")
    const loaded = await loadMigrationFile(filePath, { trustOverride: true })
    const checksum = computeMigrationChecksum(loaded)

    await writeJournal(dir, {
      version: 1,
      entries: [{ index: 1, name: migration.name, timestamp: migration.timestamp, checksum }],
    })

    // Mock client that handles advisory lock + migration queries
    const layer = mockClient({
      execute: <A = unknown>(query: string, _params?: ReadonlyArray<unknown>) => {
        if (query.includes("pg_try_advisory_lock")) {
          return Effect.succeed([{ pg_try_advisory_lock: true }] as ReadonlyArray<A>)
        }
        if (query.includes("pg_advisory_unlock")) {
          return Effect.succeed([{ pg_advisory_unlock: true }] as ReadonlyArray<A>)
        }
        // getAppliedMigrations — return empty (no migrations applied yet)
        if (query.includes("SELECT * FROM") && query.includes("_timescaledb_sdk_migrations")) {
          return Effect.succeed([] as ReadonlyArray<A>)
        }
        // All other queries (CREATE TABLE, INSERT, SELECT 1) — return empty
        return Effect.succeed([] as ReadonlyArray<A>)
      },
    })

    // With trustOverride, integrity check is skipped — should succeed with mock client
    const applied = await runTestWith(
      loadAndRun(dir, { trustOverride: true }),
      layer
    )
    expect(applied).toEqual(["0001_create_stuff"])
  })
})

describe("end-to-end generate workflow", () => {
  test("three-step schema evolution", async () => {
    // Step 1: Create initial schema
    const usersV1 = pgTable("users", {
      id: serial("id"),
      name: text("name").notNull(),
    })

    const r1 = await generate({
      definitions: [usersV1],
      migrationsDir: dir,
      description: "initial schema",
    })
    expect(r1).not.toBeNull()
    expect(r1!.up.some((s) => s.includes("CREATE TABLE"))).toBe(true)

    // Step 2: Add column
    const usersV2 = pgTable("users", {
      id: serial("id"),
      name: text("name").notNull(),
      email: text("email"),
    })

    const r2 = await generate({
      definitions: [usersV2],
      migrationsDir: dir,
      description: "add email",
    })
    expect(r2).not.toBeNull()
    expect(r2!.up.some((s) => s.includes("ADD COLUMN"))).toBe(true)

    // Step 3: Rename column
    const usersV3 = pgTable("users", {
      id: serial("id"),
      fullName: text("full_name").notNull().renamedFrom("name"),
      email: text("email"),
    })

    const r3 = await generate({
      definitions: [usersV3],
      migrationsDir: dir,
      description: "rename name to full_name",
    })
    expect(r3).not.toBeNull()
    expect(r3!.up.some((s) => s.includes("RENAME COLUMN"))).toBe(true)

    // Verify final state
    const journal = await readJournal(dir)
    expect(journal.entries.length).toBe(3)
    expect(journal.entries[0]!.name).toBe("0001_initial_schema")
    expect(journal.entries[1]!.name).toBe("0002_add_email")
    expect(journal.entries[2]!.name).toBe("0003_rename_name_to_full_name")

    const snapshot = await readSnapshot(dir)
    expect(snapshot!.definitions.tables[0]!.columns.find((c) => c.name === "full_name")).toBeDefined()
    expect(snapshot!.definitions.tables[0]!.columns.find((c) => c.name === "name")).toBeUndefined()
  })
})
