import { test, expect, describe } from "bun:test"
import { diffSchema, generateMigrationSql } from "../../src/migration/Generator.js"
import type { SchemaSnapshot } from "../../src/migration/types.js"
import {
  timestamptz, integer, doublePrecision, text, serial, boolean, varchar, uuid, numeric, jsonb, tsrange,
} from "../../src/schema/Column.js"
import { pgTable } from "../../src/schema/Table.js"
import { hypertable } from "../../src/schema/Hypertable.js"
import { expr, index, uniqueIndex, brinIndex, ginIndex } from "../../src/schema/IndexHelpers.js"
import { check, unique, foreignKey, primaryKey, exclude, deferrable } from "../../src/schema/Constraint.js"
import { pgEnum, enumColumn } from "../../src/schema/Enum.js"
import { trigger } from "../../src/schema/Trigger.js"

const emptySnapshot: SchemaSnapshot = {
  tables: [],
  hypertables: [],
  continuousAggregates: [],
  takenAt: new Date(),
}

const genUp = (defs: Parameters<typeof diffSchema>[0]) => {
  const diff = diffSchema(defs, emptySnapshot)
  return generateMigrationSql(diff, defs).up
}

const genDown = (defs: Parameters<typeof diffSchema>[0]) => {
  const diff = diffSchema(defs, emptySnapshot)
  return generateMigrationSql(diff, defs).down
}

describe("SQL Generation — CREATE TABLE", () => {
  test("basic CREATE TABLE with column types", () => {
    const users = pgTable("users", {
      id: integer("id").primaryKey(),
      name: text("name").notNull(),
      email: varchar("email", { length: 255 }),
    })
    const up = genUp([users])
    expect(up[0]).toContain('CREATE TABLE "users"')
    expect(up[0]).toContain('"id" integer PRIMARY KEY')
    expect(up[0]).toContain('"name" text NOT NULL')
    expect(up[0]).toContain('"email" varchar(255)')
  })

  test("CREATE UNLOGGED TABLE", () => {
    const t = pgTable("temp", { id: serial("id") }, undefined, { unlogged: true })
    const up = genUp([t])
    expect(up[0]).toContain("CREATE UNLOGGED TABLE")
  })

  test("CREATE TABLE IF NOT EXISTS", () => {
    const t = pgTable("events", { id: serial("id") }, undefined, { ifNotExists: true })
    const up = genUp([t])
    expect(up[0]).toContain("IF NOT EXISTS")
  })

  test("DROP TABLE IF EXISTS in down", () => {
    const users = pgTable("users", { id: serial("id") })
    const down = genDown([users])
    expect(down[0]).toContain('DROP TABLE IF EXISTS "users"')
  })
})

describe("SQL Generation — DEFAULT value quoting", () => {
  test("string default is quoted", () => {
    const t = pgTable("t", { status: text("status").default("active") })
    const up = genUp([t])
    expect(up[0]).toContain("DEFAULT 'active'")
  })

  test("numeric default is not quoted", () => {
    const t = pgTable("t", { count: integer("count").default(0) })
    const up = genUp([t])
    expect(up[0]).toContain("DEFAULT 0")
  })

  test("boolean default renders TRUE/FALSE", () => {
    const t = pgTable("t", { active: boolean("active").default(true) })
    const up = genUp([t])
    expect(up[0]).toContain("DEFAULT TRUE")
  })

  test("null default renders NULL", () => {
    const t = pgTable("t", { notes: text("notes").default(null as any) })
    const up = genUp([t])
    expect(up[0]).toContain("DEFAULT NULL")
  })

  test("string with apostrophe is escaped", () => {
    const t = pgTable("t", { name: text("name").default("O'Brien") })
    const up = genUp([t])
    expect(up[0]).toContain("DEFAULT 'O''Brien'")
  })
})

describe("SQL Generation — Column features", () => {
  test("column CHECK in output", () => {
    const t = pgTable("t", { age: integer("age").check("age >= 0") })
    const up = genUp([t])
    expect(up[0]).toContain("CHECK (age >= 0)")
  })

  test("GENERATED ALWAYS AS ... STORED", () => {
    const t = pgTable("t", {
      price: numeric("price"),
      qty: integer("qty"),
      total: numeric("total").generatedAlwaysAs("price * qty"),
    })
    const up = genUp([t])
    expect(up[0]).toContain("GENERATED ALWAYS AS (price * qty) STORED")
  })

  test("GENERATED ALWAYS AS IDENTITY", () => {
    const t = pgTable("t", { id: integer("id").generatedAlwaysAsIdentity() })
    const up = genUp([t])
    expect(up[0]).toContain("GENERATED ALWAYS AS IDENTITY")
  })

  test("GENERATED BY DEFAULT AS IDENTITY", () => {
    const t = pgTable("t", { id: integer("id").generatedByDefaultAsIdentity() })
    const up = genUp([t])
    expect(up[0]).toContain("GENERATED BY DEFAULT AS IDENTITY")
  })

  test("COLLATE in output", () => {
    const t = pgTable("t", { name: text("name").collate("en_US") })
    const up = genUp([t])
    expect(up[0]).toContain('COLLATE "en_US"')
  })

  test("REFERENCES with ON DELETE/ON UPDATE", () => {
    const t = pgTable("orders", {
      userId: integer("user_id").references("users", "id").onDelete("CASCADE").onUpdate("RESTRICT"),
    })
    const up = genUp([t])
    expect(up[0]).toContain('REFERENCES "users"("id")')
    expect(up[0]).toContain("ON DELETE CASCADE")
    expect(up[0]).toContain("ON UPDATE RESTRICT")
  })
})

describe("SQL Generation — Table-level constraints", () => {
  test("CHECK constraint", () => {
    const t = pgTable("t", { a: integer("a") }, () => [
      check("chk_a", "a > 0"),
    ])
    const up = genUp([t])
    expect(up[0]).toContain('CONSTRAINT "chk_a" CHECK (a > 0)')
  })

  test("UNIQUE constraint", () => {
    const t = pgTable("t", { a: text("a"), b: text("b") }, () => [
      unique("uq_ab", ["a", "b"]),
    ])
    const up = genUp([t])
    expect(up[0]).toContain('CONSTRAINT "uq_ab" UNIQUE ("a", "b")')
  })

  test("PRIMARY KEY constraint", () => {
    const t = pgTable("t", { a: integer("a"), b: integer("b") }, () => [
      primaryKey("pk_ab", ["a", "b"]),
    ])
    const up = genUp([t])
    expect(up[0]).toContain('CONSTRAINT "pk_ab" PRIMARY KEY ("a", "b")')
  })

  test("FOREIGN KEY constraint with actions", () => {
    const t = pgTable("orders", { userId: integer("user_id") }, () => [
      foreignKey("fk_user", ["user_id"], { table: "users", columns: ["id"] }, { onDelete: "CASCADE", onUpdate: "SET NULL" }),
    ])
    const up = genUp([t])
    expect(up[0]).toContain('CONSTRAINT "fk_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE SET NULL')
  })

  test("EXCLUDE constraint", () => {
    const t = pgTable("bookings", {
      roomId: integer("room_id"),
      during: tsrange("during"),
    }, () => [
      exclude("excl_booking", "gist", [
        { column: "room_id", operator: "=" },
        { column: "during", operator: "&&" },
      ]),
    ])
    const up = genUp([t])
    expect(up[0]).toContain('CONSTRAINT "excl_booking" EXCLUDE USING gist ("room_id" WITH =, "during" WITH &&)')
  })

  test("DEFERRABLE constraint", () => {
    const fk = foreignKey("fk_user", ["user_id"], { table: "users", columns: ["id"] })
    const t = pgTable("orders", { userId: integer("user_id") }, () => [
      deferrable(fk, "DEFERRED"),
    ])
    const up = genUp([t])
    expect(up[0]).toContain("DEFERRABLE INITIALLY DEFERRED")
  })
})

describe("SQL Generation — Indexes", () => {
  test("CREATE INDEX with btree", () => {
    const t = pgTable("users", { name: text("name") }, () => [
      index("idx_name", ["name"]),
    ])
    const up = genUp([t])
    const idxSql = up.find((s) => s.includes("CREATE INDEX"))
    expect(idxSql).toBeDefined()
    expect(idxSql).toContain('CREATE INDEX "idx_name" ON "users" USING btree ("name")')
  })

  test("CREATE UNIQUE INDEX", () => {
    const t = pgTable("users", { email: text("email") }, () => [
      uniqueIndex("idx_email", ["email"]),
    ])
    const up = genUp([t])
    const idxSql = up.find((s) => s.includes("CREATE UNIQUE INDEX"))
    expect(idxSql).toBeDefined()
  })

  test("CREATE INDEX CONCURRENTLY", () => {
    const t = pgTable("users", { name: text("name") }, () => [
      index("idx_name", ["name"], { concurrently: true }),
    ])
    const up = genUp([t])
    const idxSql = up.find((s) => s.includes("CREATE INDEX"))
    expect(idxSql).toContain("CONCURRENTLY")
  })

  test("covering index (INCLUDE)", () => {
    const t = pgTable("users", { id: integer("id"), name: text("name"), email: text("email") }, () => [
      index("idx_id", ["id"], { include: ["name", "email"] }),
    ])
    const up = genUp([t])
    const idxSql = up.find((s) => s.includes("CREATE INDEX"))
    expect(idxSql).toContain('INCLUDE ("name", "email")')
  })

  test("index with fillfactor", () => {
    const t = pgTable("users", { id: integer("id") }, () => [
      index("idx_id", ["id"], { fillfactor: 90 }),
    ])
    const up = genUp([t])
    const idxSql = up.find((s) => s.includes("CREATE INDEX"))
    expect(idxSql).toContain("WITH (fillfactor = 90)")
  })

  test("index with WHERE clause", () => {
    const t = pgTable("users", { active: boolean("active") }, () => [
      index("idx_active", ["active"], { where: "active = TRUE" }),
    ])
    const up = genUp([t])
    const idxSql = up.find((s) => s.includes("CREATE INDEX"))
    expect(idxSql).toContain("WHERE (active = TRUE)")
  })

  test("BRIN index type in SQL", () => {
    const t = pgTable("events", { time: timestamptz("time") }, () => [
      brinIndex("idx_time", ["time"]),
    ])
    const up = genUp([t])
    const idxSql = up.find((s) => s.includes("CREATE INDEX"))
    expect(idxSql).toContain("USING brin")
  })

  test("GIN index type in SQL", () => {
    const t = pgTable("docs", { tags: jsonb("tags") }, () => [
      ginIndex("idx_tags", ["tags"]),
    ])
    const up = genUp([t])
    const idxSql = up.find((s) => s.includes("CREATE INDEX"))
    expect(idxSql).toContain("USING gin")
  })
})

describe("SQL Generation — Hypertable", () => {
  test("create_hypertable SQL", () => {
    const metrics = hypertable("metrics", {
      time: timestamptz("time").notNull(),
      value: doublePrecision("value"),
    }, { timeColumn: "time", chunkInterval: "1 day" })

    const up = genUp([metrics])
    const htSql = up.find((s) => s.includes("create_hypertable"))
    expect(htSql).toBeDefined()
    expect(htSql).toContain("'metrics'")
    expect(htSql).toContain("'time'")
    expect(htSql).toContain("1 day")
  })

  test("create_hypertable with createDefaultIndexes: false", () => {
    const metrics = hypertable("metrics", {
      time: timestamptz("time").notNull(),
    }, { timeColumn: "time", createDefaultIndexes: false })

    const up = genUp([metrics])
    const htSql = up.find((s) => s.includes("create_hypertable"))
    expect(htSql).toContain("create_default_indexes => FALSE")
  })

  test("compression policy SQL", () => {
    const metrics = hypertable("metrics", {
      time: timestamptz("time").notNull(),
      deviceId: integer("device_id").notNull(),
      value: doublePrecision("value"),
    }, {
      timeColumn: "time",
      compression: {
        segmentby: ["device_id"],
        orderby: [{ column: "time", order: "DESC" }],
        after: "30 days",
      },
    })

    const up = genUp([metrics])
    const alterSql = up.find((s) => s.includes("timescaledb.compress"))
    expect(alterSql).toBeDefined()
    expect(alterSql).toContain("timescaledb.compress_segmentby = 'device_id'")
    expect(alterSql).toContain("timescaledb.compress_orderby = 'time DESC'")

    const policySql = up.find((s) => s.includes("add_compression_policy"))
    expect(policySql).toBeDefined()
    expect(policySql).toContain("INTERVAL '30 days'")
  })

  test("retention policy SQL", () => {
    const metrics = hypertable("metrics", {
      time: timestamptz("time").notNull(),
    }, {
      timeColumn: "time",
      retention: { dropAfter: "365 days" },
    })

    const up = genUp([metrics])
    const retSql = up.find((s) => s.includes("add_retention_policy"))
    expect(retSql).toBeDefined()
    expect(retSql).toContain("INTERVAL '365 days'")
  })

  test("space partitioning SQL (add_dimension)", () => {
    const metrics = hypertable("metrics", {
      time: timestamptz("time").notNull(),
      deviceId: integer("device_id").notNull(),
    }, {
      timeColumn: "time",
      partitioning: [{ column: "device_id", type: "hash", numberOfPartitions: 4 }],
    })

    const up = genUp([metrics])
    const dimSql = up.find((s) => s.includes("add_dimension"))
    expect(dimSql).toBeDefined()
    expect(dimSql).toContain("'device_id'")
    expect(dimSql).toContain("4")
  })
})

describe("SQL Generation — ALTER TABLE", () => {
  test("ADD COLUMN with default properly quoted", () => {
    const users = pgTable("users", {
      id: integer("id").primaryKey(),
      name: text("name").notNull(),
      status: text("status").notNull().default("active"),
    })

    const snapshot: SchemaSnapshot = {
      tables: [{
        name: "users",
        schema: "public",
        columns: [
          { name: "id", dataType: "integer", isNullable: false, defaultValue: null },
          { name: "name", dataType: "text", isNullable: false, defaultValue: null },
        ],
        indexes: [],
      }],
      hypertables: [],
      continuousAggregates: [],
      takenAt: new Date(),
    }

    const diff = diffSchema([users], snapshot)
    const { up, down } = generateMigrationSql(diff, [users])

    const addSql = up.find((s) => s.includes("ADD COLUMN"))
    expect(addSql).toBeDefined()
    expect(addSql).toContain("NOT NULL DEFAULT 'active'")

    const dropSql = down.find((s) => s.includes("DROP COLUMN"))
    expect(dropSql).toBeDefined()
    expect(dropSql).toContain('"status"')
  })

  test("DROP COLUMN", () => {
    const users = pgTable("users", {
      id: integer("id").primaryKey(),
    })

    const snapshot: SchemaSnapshot = {
      tables: [{
        name: "users",
        schema: "public",
        columns: [
          { name: "id", dataType: "integer", isNullable: false, defaultValue: null },
          { name: "old_col", dataType: "text", isNullable: true, defaultValue: null },
        ],
        indexes: [],
      }],
      hypertables: [],
      continuousAggregates: [],
      takenAt: new Date(),
    }

    const diff = diffSchema([users], snapshot)
    const { up } = generateMigrationSql(diff, [users])
    const dropSql = up.find((s) => s.includes("DROP COLUMN"))
    expect(dropSql).toBeDefined()
    expect(dropSql).toContain('"old_col"')
  })

  test("ALTER COLUMN TYPE", () => {
    const users = pgTable("users", {
      id: integer("id").primaryKey(),
      name: varchar("name", { length: 500 }),
    })

    const snapshot: SchemaSnapshot = {
      tables: [{
        name: "users",
        schema: "public",
        columns: [
          { name: "id", dataType: "integer", isNullable: false, defaultValue: null },
          { name: "name", dataType: "varchar(255)", isNullable: true, defaultValue: null },
        ],
        indexes: [],
      }],
      hypertables: [],
      continuousAggregates: [],
      takenAt: new Date(),
    }

    const diff = diffSchema([users], snapshot)
    const { up, down } = generateMigrationSql(diff, [users])
    const alterSql = up.find((s) => s.includes("ALTER COLUMN"))
    expect(alterSql).toBeDefined()
    expect(alterSql).toContain("TYPE varchar(500)")
    const downSql = down.find((s) => s.includes("ALTER COLUMN"))
    expect(downSql).toContain("TYPE varchar(255)")
  })

  test("DROP TABLE for tables removed from definitions", () => {
    const snapshot: SchemaSnapshot = {
      tables: [{
        name: "old_table",
        schema: "public",
        columns: [{ name: "id", dataType: "integer", isNullable: false, defaultValue: null }],
        indexes: [],
      }],
      hypertables: [],
      continuousAggregates: [],
      takenAt: new Date(),
    }

    const diff = diffSchema([], snapshot)
    const { up } = generateMigrationSql(diff, [])
    expect(up[0]).toContain('DROP TABLE IF EXISTS "old_table"')
  })
})

// ============================================
// SQL Generation — Rename Operations
// ============================================
describe("SQL Generation — Table Renames", () => {
  test("table with renamedFrom produces ALTER TABLE RENAME", () => {
    const accounts = pgTable("accounts", {
      id: serial("id"),
      name: text("name").notNull(),
    }, undefined, { renamedFrom: "users" })

    const snapshot: SchemaSnapshot = {
      tables: [{
        name: "users",
        schema: "public",
        columns: [
          { name: "id", dataType: "serial", isNullable: false, defaultValue: null },
          { name: "name", dataType: "text", isNullable: false, defaultValue: null },
        ],
        indexes: [],
      }],
      hypertables: [],
      continuousAggregates: [],
      takenAt: new Date(),
    }

    const diff = diffSchema([accounts], snapshot)
    expect(diff.tablesToRename).toEqual([{ oldName: "users", newName: "accounts" }])
    expect(diff.tablesToCreate).toEqual([])
    expect(diff.tablesToDrop).toEqual([])

    const { up, down } = generateMigrationSql(diff, [accounts])
    expect(up).toContain('ALTER TABLE "users" RENAME TO "accounts";')
    expect(down).toContain('ALTER TABLE "accounts" RENAME TO "users";')
  })

  test("stale rename hint is ignored (old name not in snapshot)", () => {
    const accounts = pgTable("accounts", {
      id: serial("id"),
    }, undefined, { renamedFrom: "users" })

    const diff = diffSchema([accounts], emptySnapshot)
    expect(diff.tablesToRename).toEqual([])
    expect(diff.tablesToCreate).toEqual(["accounts"])
  })

  test("table rename + column changes on same table", () => {
    const accounts = pgTable("accounts", {
      id: serial("id"),
      name: text("name").notNull(),
      email: text("email").notNull(),
    }, undefined, { renamedFrom: "users" })

    const snapshot: SchemaSnapshot = {
      tables: [{
        name: "users",
        schema: "public",
        columns: [
          { name: "id", dataType: "serial", isNullable: false, defaultValue: null },
          { name: "name", dataType: "text", isNullable: false, defaultValue: null },
        ],
        indexes: [],
      }],
      hypertables: [],
      continuousAggregates: [],
      takenAt: new Date(),
    }

    const diff = diffSchema([accounts], snapshot)
    expect(diff.tablesToRename.length).toBe(1)
    expect(diff.columnsToAdd.length).toBe(1)
    expect(diff.columnsToAdd[0]!.table).toBe("accounts")
    expect(diff.columnsToAdd[0]!.column).toBe("email")
  })
})

describe("SQL Generation — Column Renames", () => {
  test("column with renamedFrom produces ALTER TABLE RENAME COLUMN", () => {
    const users = pgTable("users", {
      id: serial("id"),
      fullName: text("full_name").notNull().renamedFrom("name"),
    })

    const snapshot: SchemaSnapshot = {
      tables: [{
        name: "users",
        schema: "public",
        columns: [
          { name: "id", dataType: "serial", isNullable: false, defaultValue: null },
          { name: "name", dataType: "text", isNullable: false, defaultValue: null },
        ],
        indexes: [],
      }],
      hypertables: [],
      continuousAggregates: [],
      takenAt: new Date(),
    }

    const diff = diffSchema([users], snapshot)
    expect(diff.columnsToRename).toEqual([{ table: "users", oldColumn: "name", newColumn: "full_name" }])
    expect(diff.columnsToAdd).toEqual([])
    expect(diff.columnsToRemove).toEqual([])

    const { up, down } = generateMigrationSql(diff, [users])
    expect(up).toContain('ALTER TABLE "users" RENAME COLUMN "name" TO "full_name";')
    expect(down).toContain('ALTER TABLE "users" RENAME COLUMN "full_name" TO "name";')
  })

  test("no rename hint = drop + add (backward compatible)", () => {
    const users = pgTable("users", {
      id: serial("id"),
      fullName: text("full_name").notNull(),
    })

    const snapshot: SchemaSnapshot = {
      tables: [{
        name: "users",
        schema: "public",
        columns: [
          { name: "id", dataType: "serial", isNullable: false, defaultValue: null },
          { name: "name", dataType: "text", isNullable: false, defaultValue: null },
        ],
        indexes: [],
      }],
      hypertables: [],
      continuousAggregates: [],
      takenAt: new Date(),
    }

    const diff = diffSchema([users], snapshot)
    expect(diff.columnsToRename).toEqual([])
    expect(diff.columnsToAdd.length).toBe(1)
    expect(diff.columnsToRemove.length).toBe(1)
  })

  test("stale column rename hint ignored", () => {
    const users = pgTable("users", {
      id: serial("id"),
      fullName: text("full_name").notNull().renamedFrom("name"),
    })

    // Snapshot already has full_name (rename already happened)
    const snapshot: SchemaSnapshot = {
      tables: [{
        name: "users",
        schema: "public",
        columns: [
          { name: "id", dataType: "serial", isNullable: false, defaultValue: null },
          { name: "full_name", dataType: "text", isNullable: false, defaultValue: null },
        ],
        indexes: [],
      }],
      hypertables: [],
      continuousAggregates: [],
      takenAt: new Date(),
    }

    const diff = diffSchema([users], snapshot)
    expect(diff.columnsToRename).toEqual([])
    expect(diff.columnsToAdd).toEqual([])
    expect(diff.columnsToRemove).toEqual([])
  })

  test("column rename on renamed table works", () => {
    const accounts = pgTable("accounts", {
      id: serial("id"),
      fullName: text("full_name").notNull().renamedFrom("name"),
    }, undefined, { renamedFrom: "users" })

    const snapshot: SchemaSnapshot = {
      tables: [{
        name: "users",
        schema: "public",
        columns: [
          { name: "id", dataType: "serial", isNullable: false, defaultValue: null },
          { name: "name", dataType: "text", isNullable: false, defaultValue: null },
        ],
        indexes: [],
      }],
      hypertables: [],
      continuousAggregates: [],
      takenAt: new Date(),
    }

    const diff = diffSchema([accounts], snapshot)
    expect(diff.tablesToRename).toEqual([{ oldName: "users", newName: "accounts" }])
    expect(diff.columnsToRename).toEqual([{ table: "accounts", oldColumn: "name", newColumn: "full_name" }])

    const { up } = generateMigrationSql(diff, [accounts])
    const renameTableIdx = up.findIndex((s) => s.includes("RENAME TO"))
    const renameColIdx = up.findIndex((s) => s.includes("RENAME COLUMN"))
    expect(renameTableIdx).toBeGreaterThanOrEqual(0)
    expect(renameColIdx).toBeGreaterThan(renameTableIdx)
  })

  test("rename SQL order: table renames before column renames before adds", () => {
    const accounts = pgTable("accounts", {
      id: serial("id"),
      fullName: text("full_name").notNull().renamedFrom("name"),
      email: text("email").notNull(),
    }, undefined, { renamedFrom: "users" })

    const snapshot: SchemaSnapshot = {
      tables: [{
        name: "users",
        schema: "public",
        columns: [
          { name: "id", dataType: "serial", isNullable: false, defaultValue: null },
          { name: "name", dataType: "text", isNullable: false, defaultValue: null },
        ],
        indexes: [],
      }],
      hypertables: [],
      continuousAggregates: [],
      takenAt: new Date(),
    }

    const diff = diffSchema([accounts], snapshot)
    const { up } = generateMigrationSql(diff, [accounts])

    const renameTableIdx = up.findIndex((s) => s.includes("RENAME TO"))
    const renameColIdx = up.findIndex((s) => s.includes("RENAME COLUMN"))
    const addColIdx = up.findIndex((s) => s.includes("ADD COLUMN"))
    expect(renameTableIdx).toBeLessThan(renameColIdx)
    expect(renameColIdx).toBeLessThan(addColIdx)
  })
})

// ============================================
// SQL Generation — Expression-based Indexes (Phase 1)
// ============================================
describe("SQL Generation — Expression-based Indexes", () => {
  test("expression index produces parenthesized expression", () => {
    const t = pgTable("users", { name: text("name") }, () => [
      index("idx_lower_name", [expr("lower(name)")]),
    ])
    const up = genUp([t])
    const idxSql = up.find((s) => s.includes("CREATE INDEX"))
    expect(idxSql).toContain("((lower(name)))")
  })

  test("expression with opclass", () => {
    const t = pgTable("users", { name: text("name") }, () => [
      index("idx_pattern", [expr("lower(name)", "text_pattern_ops")]),
    ])
    const up = genUp([t])
    const idxSql = up.find((s) => s.includes("CREATE INDEX"))
    expect(idxSql).toContain("(lower(name)) text_pattern_ops")
  })

  test("mixed string and expression columns", () => {
    const t = pgTable("events", {
      id: integer("id"),
      name: text("name"),
    }, () => [
      index("idx_mixed", ["id", expr("lower(name)")]),
    ])
    const up = genUp([t])
    const idxSql = up.find((s) => s.includes("CREATE INDEX"))
    expect(idxSql).toContain('"id", (lower(name))')
  })

  test("existing string columns still produce quoted identifiers", () => {
    const t = pgTable("users", { name: text("name") }, () => [
      index("idx_name", ["name"]),
    ])
    const up = genUp([t])
    const idxSql = up.find((s) => s.includes("CREATE INDEX"))
    expect(idxSql).toContain('("name")')
  })
})

// ============================================
// SQL Generation — Enum Types (Phase 2)
// ============================================
describe("SQL Generation — Enum Types", () => {
  test("CREATE TYPE AS ENUM", () => {
    const status = pgEnum("status", ["active", "inactive"] as const)
    const up = genUp([status])
    expect(up[0]).toContain('CREATE TYPE "status" AS ENUM')
    expect(up[0]).toContain("'active', 'inactive'")
  })

  test("enum appears before CREATE TABLE", () => {
    const status = pgEnum("status", ["active", "inactive"] as const)
    const t = pgTable("users", {
      id: serial("id"),
      status: enumColumn(status, "status").notNull(),
    })
    const up = genUp([status, t])
    const enumIdx = up.findIndex((s) => s.includes("CREATE TYPE"))
    const tableIdx = up.findIndex((s) => s.includes("CREATE TABLE"))
    expect(enumIdx).toBeLessThan(tableIdx)
  })

  test("DROP TYPE in down migration", () => {
    const status = pgEnum("status", ["active", "inactive"] as const)
    const down = genDown([status])
    expect(down[0]).toContain('DROP TYPE IF EXISTS "status"')
  })

  test("enum with values containing apostrophes", () => {
    const status = pgEnum("status", ["it's active", "normal"] as const)
    const up = genUp([status])
    expect(up[0]).toContain("'it''s active'")
  })

  test("table with enum column", () => {
    const status = pgEnum("status", ["active", "inactive"] as const)
    const t = pgTable("users", {
      id: serial("id"),
      status: enumColumn(status, "status").notNull().default("active"),
    })
    const up = genUp([status, t])
    const tableSql = up.find((s) => s.includes("CREATE TABLE"))
    expect(tableSql).toContain('"status" status NOT NULL')
    expect(tableSql).toContain("DEFAULT 'active'")
  })
})

// ============================================
// SQL Generation — Modern Hypertable WITH Syntax (Phase 4)
// ============================================
describe("SQL Generation — Modern Hypertable WITH Syntax", () => {
  test("modern syntax produces WITH clause", () => {
    const metrics = hypertable("metrics", {
      time: timestamptz("time").notNull(),
      value: doublePrecision("value"),
    }, {
      timeColumn: "time",
      chunkInterval: "1 day",
      useModernSyntax: true,
    })

    const up = genUp([metrics])
    const createSql = up.find((s) => s.includes("CREATE TABLE"))
    expect(createSql).toContain("tsdb.hypertable")
    expect(createSql).toContain("tsdb.time_column = 'time'")
    expect(createSql).toContain("tsdb.chunk_interval = '1 day'")
    // Should NOT have create_hypertable call
    expect(up.find((s) => s.includes("create_hypertable"))).toBeUndefined()
  })

  test("modern syntax with compression and retention", () => {
    const metrics = hypertable("metrics", {
      time: timestamptz("time").notNull(),
      deviceId: integer("device_id").notNull(),
      value: doublePrecision("value"),
    }, {
      timeColumn: "time",
      chunkInterval: "1 day",
      useModernSyntax: true,
      compression: {
        segmentby: ["device_id"],
        orderby: [{ column: "time", order: "DESC" }],
        after: "30 days",
      },
      retention: { dropAfter: "365 days" },
    })

    const up = genUp([metrics])
    const createSql = up.find((s) => s.includes("CREATE TABLE"))
    expect(createSql).toContain("tsdb.segmentby = 'device_id'")
    expect(createSql).toContain("tsdb.orderby = 'time DESC'")
    expect(createSql).toContain("tsdb.compress_after = '30 days'")
    expect(createSql).toContain("tsdb.retention_after = '365 days'")
  })

  test("legacy syntax unchanged when useModernSyntax not set", () => {
    const metrics = hypertable("metrics", {
      time: timestamptz("time").notNull(),
    }, { timeColumn: "time", chunkInterval: "1 day" })

    const up = genUp([metrics])
    expect(up.find((s) => s.includes("create_hypertable"))).toBeDefined()
    const createSql = up.find((s) => s.includes("CREATE TABLE"))
    expect(createSql).not.toContain("tsdb.hypertable")
  })

  test("migrateData in legacy syntax", () => {
    const metrics = hypertable("metrics", {
      time: timestamptz("time").notNull(),
    }, {
      timeColumn: "time",
      migrateData: true,
    })

    const up = genUp([metrics])
    const htSql = up.find((s) => s.includes("create_hypertable"))
    expect(htSql).toContain("migrate_data => TRUE")
  })
})

// ============================================
// SQL Generation — Triggers (Phase 5)
// ============================================
describe("SQL Generation — Triggers", () => {
  test("BEFORE INSERT trigger", () => {
    const t = pgTable("users", { id: serial("id"), name: text("name") }, () => [
      trigger("trg_before_insert", {
        timing: "BEFORE",
        events: ["INSERT"],
        forEach: "ROW",
        functionName: "set_created_at",
      }),
    ])
    const up = genUp([t])
    const trgSql = up.find((s) => s.includes("CREATE TRIGGER"))
    expect(trgSql).toContain('CREATE TRIGGER "trg_before_insert" BEFORE INSERT ON "users" FOR EACH ROW EXECUTE FUNCTION set_created_at()')
  })

  test("AFTER UPDATE trigger with columns", () => {
    const t = pgTable("users", { id: serial("id"), name: text("name"), email: text("email") }, () => [
      trigger("trg_after_update", {
        timing: "AFTER",
        events: ["UPDATE"],
        forEach: "ROW",
        functionName: "notify_change",
        columns: ["name", "email"],
      }),
    ])
    const up = genUp([t])
    const trgSql = up.find((s) => s.includes("CREATE TRIGGER"))
    expect(trgSql).toContain('AFTER UPDATE OF "name", "email" ON "users"')
  })

  test("trigger with multiple events", () => {
    const t = pgTable("audit_log", { id: serial("id") }, () => [
      trigger("trg_audit", {
        timing: "AFTER",
        events: ["INSERT", "DELETE"],
        forEach: "ROW",
        functionName: "audit_func",
      }),
    ])
    const up = genUp([t])
    const trgSql = up.find((s) => s.includes("CREATE TRIGGER"))
    expect(trgSql).toContain("AFTER INSERT OR DELETE")
  })

  test("trigger with WHEN clause", () => {
    const t = pgTable("orders", { id: serial("id"), status: text("status") }, () => [
      trigger("trg_status_change", {
        timing: "AFTER",
        events: ["UPDATE"],
        forEach: "ROW",
        functionName: "notify_status",
        when: "OLD.status IS DISTINCT FROM NEW.status",
      }),
    ])
    const up = genUp([t])
    const trgSql = up.find((s) => s.includes("CREATE TRIGGER"))
    expect(trgSql).toContain("WHEN (OLD.status IS DISTINCT FROM NEW.status)")
  })

  test("INSTEAD OF trigger with STATEMENT", () => {
    const t = pgTable("events", { id: serial("id") }, () => [
      trigger("trg_instead", {
        timing: "INSTEAD OF",
        events: ["INSERT"],
        forEach: "STATEMENT",
        functionName: "redirect_insert",
      }),
    ])
    const up = genUp([t])
    const trgSql = up.find((s) => s.includes("CREATE TRIGGER"))
    expect(trgSql).toContain("INSTEAD OF INSERT")
    expect(trgSql).toContain("FOR EACH STATEMENT")
  })

  test("DROP TRIGGER in down migration", () => {
    const t = pgTable("users", { id: serial("id") }, () => [
      trigger("trg_test", {
        timing: "BEFORE",
        events: ["INSERT"],
        forEach: "ROW",
        functionName: "test_func",
      }),
    ])
    const down = genDown([t])
    const dropTrg = down.find((s) => s.includes("DROP TRIGGER"))
    expect(dropTrg).toContain('DROP TRIGGER IF EXISTS "trg_test" ON "users"')
  })
})
