import { test, expect, describe } from "bun:test"
import { diffSchema, generateMigrationSql } from "../../src/migration/Generator.js"
import type { SchemaSnapshot } from "../../src/migration/types.js"
import {
  timestamptz, integer, doublePrecision, text, serial, boolean, varchar, uuid, numeric, jsonb, tsrange,
} from "../../src/schema/Column.js"
import { pgTable } from "../../src/schema/Table.js"
import { hypertable } from "../../src/schema/Hypertable.js"
import { index, uniqueIndex, brinIndex, ginIndex } from "../../src/schema/IndexHelpers.js"
import { check, unique, foreignKey, primaryKey, exclude, deferrable } from "../../src/schema/Constraint.js"

const emptySnapshot: SchemaSnapshot = {
  tables: [],
  hypertables: [],
  continuousAggregates: [],
  takenAt: new Date(),
}

const genUp = (defs: Parameters<typeof diffSchema>[0]) => {
  const diff = diffSchema(defs, emptySnapshot)
  return generateMigrationSql(diff, defs).up
}

const genDown = (defs: Parameters<typeof diffSchema>[0]) => {
  const diff = diffSchema(defs, emptySnapshot)
  return generateMigrationSql(diff, defs).down
}

describe("SQL Generation — CREATE TABLE", () => {
  test("basic CREATE TABLE with column types", () => {
    const users = pgTable("users", {
      id: integer("id").primaryKey(),
      name: text("name").notNull(),
      email: varchar("email", { length: 255 }),
    })
    const up = genUp([users])
    expect(up[0]).toContain('CREATE TABLE "users"')
    expect(up[0]).toContain('"id" integer PRIMARY KEY')
    expect(up[0]).toContain('"name" text NOT NULL')
    expect(up[0]).toContain('"email" varchar(255)')
  })

  test("CREATE UNLOGGED TABLE", () => {
    const t = pgTable("temp", { id: serial("id") }, undefined, { unlogged: true })
    const up = genUp([t])
    expect(up[0]).toContain("CREATE UNLOGGED TABLE")
  })

  test("CREATE TABLE IF NOT EXISTS", () => {
    const t = pgTable("events", { id: serial("id") }, undefined, { ifNotExists: true })
    const up = genUp([t])
    expect(up[0]).toContain("IF NOT EXISTS")
  })

  test("DROP TABLE IF EXISTS in down", () => {
    const users = pgTable("users", { id: serial("id") })
    const down = genDown([users])
    expect(down[0]).toContain('DROP TABLE IF EXISTS "users"')
  })
})

describe("SQL Generation — DEFAULT value quoting", () => {
  test("string default is quoted", () => {
    const t = pgTable("t", { status: text("status").default("active") })
    const up = genUp([t])
    expect(up[0]).toContain("DEFAULT 'active'")
  })

  test("numeric default is not quoted", () => {
    const t = pgTable("t", { count: integer("count").default(0) })
    const up = genUp([t])
    expect(up[0]).toContain("DEFAULT 0")
  })

  test("boolean default renders TRUE/FALSE", () => {
    const t = pgTable("t", { active: boolean("active").default(true) })
    const up = genUp([t])
    expect(up[0]).toContain("DEFAULT TRUE")
  })

  test("null default renders NULL", () => {
    const t = pgTable("t", { notes: text("notes").default(null as any) })
    const up = genUp([t])
    expect(up[0]).toContain("DEFAULT NULL")
  })

  test("string with apostrophe is escaped", () => {
    const t = pgTable("t", { name: text("name").default("O'Brien") })
    const up = genUp([t])
    expect(up[0]).toContain("DEFAULT 'O''Brien'")
  })
})

describe("SQL Generation — Column features", () => {
  test("column CHECK in output", () => {
    const t = pgTable("t", { age: integer("age").check("age >= 0") })
    const up = genUp([t])
    expect(up[0]).toContain("CHECK (age >= 0)")
  })

  test("GENERATED ALWAYS AS ... STORED", () => {
    const t = pgTable("t", {
      price: numeric("price"),
      qty: integer("qty"),
      total: numeric("total").generatedAlwaysAs("price * qty"),
    })
    const up = genUp([t])
    expect(up[0]).toContain("GENERATED ALWAYS AS (price * qty) STORED")
  })

  test("GENERATED ALWAYS AS IDENTITY", () => {
    const t = pgTable("t", { id: integer("id").generatedAlwaysAsIdentity() })
    const up = genUp([t])
    expect(up[0]).toContain("GENERATED ALWAYS AS IDENTITY")
  })

  test("GENERATED BY DEFAULT AS IDENTITY", () => {
    const t = pgTable("t", { id: integer("id").generatedByDefaultAsIdentity() })
    const up = genUp([t])
    expect(up[0]).toContain("GENERATED BY DEFAULT AS IDENTITY")
  })

  test("COLLATE in output", () => {
    const t = pgTable("t", { name: text("name").collate("en_US") })
    const up = genUp([t])
    expect(up[0]).toContain('COLLATE "en_US"')
  })

  test("REFERENCES with ON DELETE/ON UPDATE", () => {
    const t = pgTable("orders", {
      userId: integer("user_id").references("users", "id").onDelete("CASCADE").onUpdate("RESTRICT"),
    })
    const up = genUp([t])
    expect(up[0]).toContain('REFERENCES "users"("id")')
    expect(up[0]).toContain("ON DELETE CASCADE")
    expect(up[0]).toContain("ON UPDATE RESTRICT")
  })
})

describe("SQL Generation — Table-level constraints", () => {
  test("CHECK constraint", () => {
    const t = pgTable("t", { a: integer("a") }, () => [
      check("chk_a", "a > 0"),
    ])
    const up = genUp([t])
    expect(up[0]).toContain('CONSTRAINT "chk_a" CHECK (a > 0)')
  })

  test("UNIQUE constraint", () => {
    const t = pgTable("t", { a: text("a"), b: text("b") }, () => [
      unique("uq_ab", ["a", "b"]),
    ])
    const up = genUp([t])
    expect(up[0]).toContain('CONSTRAINT "uq_ab" UNIQUE ("a", "b")')
  })

  test("PRIMARY KEY constraint", () => {
    const t = pgTable("t", { a: integer("a"), b: integer("b") }, () => [
      primaryKey("pk_ab", ["a", "b"]),
    ])
    const up = genUp([t])
    expect(up[0]).toContain('CONSTRAINT "pk_ab" PRIMARY KEY ("a", "b")')
  })

  test("FOREIGN KEY constraint with actions", () => {
    const t = pgTable("orders", { userId: integer("user_id") }, () => [
      foreignKey("fk_user", ["user_id"], { table: "users", columns: ["id"] }, { onDelete: "CASCADE", onUpdate: "SET NULL" }),
    ])
    const up = genUp([t])
    expect(up[0]).toContain('CONSTRAINT "fk_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE SET NULL')
  })

  test("EXCLUDE constraint", () => {
    const t = pgTable("bookings", {
      roomId: integer("room_id"),
      during: tsrange("during"),
    }, () => [
      exclude("excl_booking", "gist", [
        { column: "room_id", operator: "=" },
        { column: "during", operator: "&&" },
      ]),
    ])
    const up = genUp([t])
    expect(up[0]).toContain('CONSTRAINT "excl_booking" EXCLUDE USING gist ("room_id" WITH =, "during" WITH &&)')
  })

  test("DEFERRABLE constraint", () => {
    const fk = foreignKey("fk_user", ["user_id"], { table: "users", columns: ["id"] })
    const t = pgTable("orders", { userId: integer("user_id") }, () => [
      deferrable(fk, "DEFERRED"),
    ])
    const up = genUp([t])
    expect(up[0]).toContain("DEFERRABLE INITIALLY DEFERRED")
  })
})

describe("SQL Generation — Indexes", () => {
  test("CREATE INDEX with btree", () => {
    const t = pgTable("users", { name: text("name") }, () => [
      index("idx_name", ["name"]),
    ])
    const up = genUp([t])
    const idxSql = up.find((s) => s.includes("CREATE INDEX"))
    expect(idxSql).toBeDefined()
    expect(idxSql).toContain('CREATE INDEX "idx_name" ON "users" USING btree ("name")')
  })

  test("CREATE UNIQUE INDEX", () => {
    const t = pgTable("users", { email: text("email") }, () => [
      uniqueIndex("idx_email", ["email"]),
    ])
    const up = genUp([t])
    const idxSql = up.find((s) => s.includes("CREATE UNIQUE INDEX"))
    expect(idxSql).toBeDefined()
  })

  test("CREATE INDEX CONCURRENTLY", () => {
    const t = pgTable("users", { name: text("name") }, () => [
      index("idx_name", ["name"], { concurrently: true }),
    ])
    const up = genUp([t])
    const idxSql = up.find((s) => s.includes("CREATE INDEX"))
    expect(idxSql).toContain("CONCURRENTLY")
  })

  test("covering index (INCLUDE)", () => {
    const t = pgTable("users", { id: integer("id"), name: text("name"), email: text("email") }, () => [
      index("idx_id", ["id"], { include: ["name", "email"] }),
    ])
    const up = genUp([t])
    const idxSql = up.find((s) => s.includes("CREATE INDEX"))
    expect(idxSql).toContain('INCLUDE ("name", "email")')
  })

  test("index with fillfactor", () => {
    const t = pgTable("users", { id: integer("id") }, () => [
      index("idx_id", ["id"], { fillfactor: 90 }),
    ])
    const up = genUp([t])
    const idxSql = up.find((s) => s.includes("CREATE INDEX"))
    expect(idxSql).toContain("WITH (fillfactor = 90)")
  })

  test("index with WHERE clause", () => {
    const t = pgTable("users", { active: boolean("active") }, () => [
      index("idx_active", ["active"], { where: "active = TRUE" }),
    ])
    const up = genUp([t])
    const idxSql = up.find((s) => s.includes("CREATE INDEX"))
    expect(idxSql).toContain("WHERE (active = TRUE)")
  })

  test("BRIN index type in SQL", () => {
    const t = pgTable("events", { time: timestamptz("time") }, () => [
      brinIndex("idx_time", ["time"]),
    ])
    const up = genUp([t])
    const idxSql = up.find((s) => s.includes("CREATE INDEX"))
    expect(idxSql).toContain("USING brin")
  })

  test("GIN index type in SQL", () => {
    const t = pgTable("docs", { tags: jsonb("tags") }, () => [
      ginIndex("idx_tags", ["tags"]),
    ])
    const up = genUp([t])
    const idxSql = up.find((s) => s.includes("CREATE INDEX"))
    expect(idxSql).toContain("USING gin")
  })
})

describe("SQL Generation — Hypertable", () => {
  test("create_hypertable SQL", () => {
    const metrics = hypertable("metrics", {
      time: timestamptz("time").notNull(),
      value: doublePrecision("value"),
    }, { timeColumn: "time", chunkInterval: "1 day" })

    const up = genUp([metrics])
    const htSql = up.find((s) => s.includes("create_hypertable"))
    expect(htSql).toBeDefined()
    expect(htSql).toContain("'metrics'")
    expect(htSql).toContain("'time'")
    expect(htSql).toContain("1 day")
  })

  test("create_hypertable with createDefaultIndexes: false", () => {
    const metrics = hypertable("metrics", {
      time: timestamptz("time").notNull(),
    }, { timeColumn: "time", createDefaultIndexes: false })

    const up = genUp([metrics])
    const htSql = up.find((s) => s.includes("create_hypertable"))
    expect(htSql).toContain("create_default_indexes => FALSE")
  })

  test("compression policy SQL", () => {
    const metrics = hypertable("metrics", {
      time: timestamptz("time").notNull(),
      deviceId: integer("device_id").notNull(),
      value: doublePrecision("value"),
    }, {
      timeColumn: "time",
      compression: {
        segmentby: ["device_id"],
        orderby: [{ column: "time", order: "DESC" }],
        after: "30 days",
      },
    })

    const up = genUp([metrics])
    const alterSql = up.find((s) => s.includes("timescaledb.compress"))
    expect(alterSql).toBeDefined()
    expect(alterSql).toContain("timescaledb.compress_segmentby = 'device_id'")
    expect(alterSql).toContain("timescaledb.compress_orderby = 'time DESC'")

    const policySql = up.find((s) => s.includes("add_compression_policy"))
    expect(policySql).toBeDefined()
    expect(policySql).toContain("INTERVAL '30 days'")
  })

  test("retention policy SQL", () => {
    const metrics = hypertable("metrics", {
      time: timestamptz("time").notNull(),
    }, {
      timeColumn: "time",
      retention: { dropAfter: "365 days" },
    })

    const up = genUp([metrics])
    const retSql = up.find((s) => s.includes("add_retention_policy"))
    expect(retSql).toBeDefined()
    expect(retSql).toContain("INTERVAL '365 days'")
  })

  test("space partitioning SQL (add_dimension)", () => {
    const metrics = hypertable("metrics", {
      time: timestamptz("time").notNull(),
      deviceId: integer("device_id").notNull(),
    }, {
      timeColumn: "time",
      partitioning: [{ column: "device_id", type: "hash", numberOfPartitions: 4 }],
    })

    const up = genUp([metrics])
    const dimSql = up.find((s) => s.includes("add_dimension"))
    expect(dimSql).toBeDefined()
    expect(dimSql).toContain("'device_id'")
    expect(dimSql).toContain("4")
  })
})

describe("SQL Generation — ALTER TABLE", () => {
  test("ADD COLUMN with default properly quoted", () => {
    const users = pgTable("users", {
      id: integer("id").primaryKey(),
      name: text("name").notNull(),
      status: text("status").notNull().default("active"),
    })

    const snapshot: SchemaSnapshot = {
      tables: [{
        name: "users",
        schema: "public",
        columns: [
          { name: "id", dataType: "integer", isNullable: false, defaultValue: null },
          { name: "name", dataType: "text", isNullable: false, defaultValue: null },
        ],
        indexes: [],
      }],
      hypertables: [],
      continuousAggregates: [],
      takenAt: new Date(),
    }

    const diff = diffSchema([users], snapshot)
    const { up, down } = generateMigrationSql(diff, [users])

    const addSql = up.find((s) => s.includes("ADD COLUMN"))
    expect(addSql).toBeDefined()
    expect(addSql).toContain("NOT NULL DEFAULT 'active'")

    const dropSql = down.find((s) => s.includes("DROP COLUMN"))
    expect(dropSql).toBeDefined()
    expect(dropSql).toContain('"status"')
  })

  test("DROP COLUMN", () => {
    const users = pgTable("users", {
      id: integer("id").primaryKey(),
    })

    const snapshot: SchemaSnapshot = {
      tables: [{
        name: "users",
        schema: "public",
        columns: [
          { name: "id", dataType: "integer", isNullable: false, defaultValue: null },
          { name: "old_col", dataType: "text", isNullable: true, defaultValue: null },
        ],
        indexes: [],
      }],
      hypertables: [],
      continuousAggregates: [],
      takenAt: new Date(),
    }

    const diff = diffSchema([users], snapshot)
    const { up } = generateMigrationSql(diff, [users])
    const dropSql = up.find((s) => s.includes("DROP COLUMN"))
    expect(dropSql).toBeDefined()
    expect(dropSql).toContain('"old_col"')
  })

  test("ALTER COLUMN TYPE", () => {
    const users = pgTable("users", {
      id: integer("id").primaryKey(),
      name: varchar("name", { length: 500 }),
    })

    const snapshot: SchemaSnapshot = {
      tables: [{
        name: "users",
        schema: "public",
        columns: [
          { name: "id", dataType: "integer", isNullable: false, defaultValue: null },
          { name: "name", dataType: "varchar(255)", isNullable: true, defaultValue: null },
        ],
        indexes: [],
      }],
      hypertables: [],
      continuousAggregates: [],
      takenAt: new Date(),
    }

    const diff = diffSchema([users], snapshot)
    const { up, down } = generateMigrationSql(diff, [users])
    const alterSql = up.find((s) => s.includes("ALTER COLUMN"))
    expect(alterSql).toBeDefined()
    expect(alterSql).toContain("TYPE varchar(500)")
    const downSql = down.find((s) => s.includes("ALTER COLUMN"))
    expect(downSql).toContain("TYPE varchar(255)")
  })

  test("DROP TABLE for tables removed from definitions", () => {
    const snapshot: SchemaSnapshot = {
      tables: [{
        name: "old_table",
        schema: "public",
        columns: [{ name: "id", dataType: "integer", isNullable: false, defaultValue: null }],
        indexes: [],
      }],
      hypertables: [],
      continuousAggregates: [],
      takenAt: new Date(),
    }

    const diff = diffSchema([], snapshot)
    const { up } = generateMigrationSql(diff, [])
    expect(up[0]).toContain('DROP TABLE IF EXISTS "old_table"')
  })
})
